// packages/angular/src/components/link/link.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';
import { LucideAngularModule, ExternalLink } from 'lucide-angular';

type LucideIconData = typeof ExternalLink;

export type OriLinkVariant = 'default' | 'quiet';

function isExternalUrl(href: string | undefined): boolean {
  if (!href) return false;
  return /^(https?:|\/\/)/i.test(href);
}

/**
 * Lien stylé avec détection automatique des URLs externes
 * (`target="_blank"` + `rel="noreferrer noopener"` + icône + libellé
 * caché « nouvel onglet » pour les lecteurs d'écran).
 */
@Component({
  selector: 'ori-link',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <a [href]="href" [class]="linkClasses" [attr.target]="finalTarget" [attr.rel]="finalRel">
      <ng-content></ng-content>
      @if (isExternal) {
        <lucide-icon
          [img]="ExternalIcon"
          [size]="14"
          class="ori-link__external"
          aria-hidden="true"
        ></lucide-icon>
        <span
          style="position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;"
        >
          (nouvel onglet)
        </span>
      }
    </a>
  `,
})
export class OriLinkComponent {
  @Input() href: string = '';
  @Input() variant: OriLinkVariant = 'default';
  @Input() target: string = '';
  @Input() rel: string = '';
  /**
   * Force l'externalité du lien. Si non fourni, détecté à partir de
   * `href` (commence par `http(s):` ou `//`).
   */
  @Input() external: boolean | null = null;

  protected readonly ExternalIcon: LucideIconData = ExternalLink;

  get isExternal(): boolean {
    return this.external ?? isExternalUrl(this.href);
  }

  get finalTarget(): string | null {
    if (this.target) return this.target;
    return this.isExternal ? '_blank' : null;
  }

  get finalRel(): string | null {
    if (this.rel) return this.rel;
    return this.isExternal ? 'noreferrer noopener' : null;
  }

  get linkClasses(): string {
    return ['ori-link', this.variant === 'quiet' ? 'ori-link--quiet' : null]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }
}

// packages/react/src/components/Link/Link.tsx
import { forwardRef, type AnchorHTMLAttributes, type ReactNode } from 'react';
import { clsx } from 'clsx';
import { ExternalLink } from 'lucide-react';

export type LinkVariant = 'default' | 'quiet';

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  variant?: LinkVariant;
  /**
   * Si `true`, ajoute `target="_blank"` + `rel="noreferrer noopener"`
   * + une icône externe et un texte d'aide pour les lecteurs d'écran.
   * Détecté automatiquement si `href` commence par `http(s):` ou
   * démarre par `//`. Forcer à `false` pour désactiver.
   */
  external?: boolean;
  children?: ReactNode;
}

function isExternalUrl(href: string | undefined): boolean {
  if (!href) return false;
  return /^(https?:|\/\/)/i.test(href);
}

/**
 * Lien stylé : `<a>` natif avec couleur primaire et focus visible.
 *
 * Variante `quiet` : couleur héritée, soulignement uniquement au hover
 * (utile dans des listes de liens denses où le bleu serait trop fort).
 *
 * Détection automatique des liens externes : ajoute `target="_blank"`
 * + `rel="noreferrer noopener"` + icône + libellé "(nouvel onglet)" pour
 * les lecteurs d'écran.
 */
export const Link = forwardRef<HTMLAnchorElement, LinkProps>(function Link(
  { variant = 'default', external, className, children, href, target, rel, ...rest },
  ref,
) {
  const isExternal = external ?? isExternalUrl(href);
  const finalTarget = target ?? (isExternal ? '_blank' : undefined);
  const finalRel = rel ?? (isExternal ? 'noreferrer noopener' : undefined);

  return (
    <a
      ref={ref}
      href={href}
      target={finalTarget}
      rel={finalRel}
      className={clsx('ori-link', variant === 'quiet' && 'ori-link--quiet', className)}
      {...rest}
    >
      {children}
      {isExternal && (
        <>
          <ExternalLink size={14} className="ori-link__external" aria-hidden="true" />
          <span
            style={{
              position: 'absolute',
              width: 1,
              height: 1,
              padding: 0,
              margin: -1,
              overflow: 'hidden',
              clip: 'rect(0,0,0,0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
          >
            (nouvel onglet)
          </span>
        </>
      )}
    </a>
  );
});
