// packages/angular/src/components/accordion/accordion.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  Renderer2,
  ViewChild,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { LucideAngularModule, ChevronDown } from 'lucide-angular';

type LucideIconData = typeof ChevronDown;

let nextUid = 0;

/**
 * Accordéon basé sur `<details>` / `<summary>` natifs HTML
 * (cf. décision F.1).
 *
 * Mode `single` : utilise l'attribut natif `name` partagé pour rendre
 * les items mutuellement exclusifs (Chrome 120+, Firefox 122+, Safari 17+).
 * Mode `multiple` : pas d'attribut `name`.
 */
@Component({
  selector: 'ori-accordion',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="ori-accordion">
      <ng-content></ng-content>
    </div>
  `,
})
export class OriAccordionComponent {
  @Input() type: 'single' | 'multiple' = 'multiple';

  private readonly autoId = `pf-accordion-${++nextUid}`;

  /** Nom partagé entre les items en mode `single` (null en mode `multiple`). */
  get groupName(): string | null {
    return this.type === 'single' ? this.autoId : null;
  }
}

/**
 * Item d'un `<ori-accordion>`. Wrappe `<details>` + `<summary>`.
 *
 * Récupère le parent `OriAccordionComponent` via injection et applique
 * l'attribut natif `name` sur le `<details>` au montage si le parent
 * est en mode `single`.
 */
@Component({
  selector: 'ori-accordion-item',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <details #detailsEl class="ori-accordion__item" [open]="defaultOpen">
      <summary class="ori-accordion__summary">
        <span>{{ title }}</span>
        <lucide-icon
          [img]="ChevronIcon"
          [size]="18"
          class="ori-accordion__chevron"
          aria-hidden="true"
        ></lucide-icon>
      </summary>
      <div class="ori-accordion__content">
        <ng-content></ng-content>
      </div>
    </details>
  `,
})
export class OriAccordionItemComponent implements AfterViewInit {
  @Input() title: string = '';
  @Input() defaultOpen: boolean = false;

  @ViewChild('detailsEl') private detailsEl?: ElementRef<HTMLDetailsElement>;

  private readonly accordion = inject(OriAccordionComponent, { optional: true });
  private readonly renderer = inject(Renderer2);

  protected readonly ChevronIcon: LucideIconData = ChevronDown;

  ngAfterViewInit(): void {
    const groupName = this.accordion?.groupName;
    if (groupName && this.detailsEl) {
      this.renderer.setAttribute(this.detailsEl.nativeElement, 'name', groupName);
    }
  }
}

// packages/react/src/components/Accordion/Accordion.tsx
import { useId, type ReactNode } from 'react';
import { clsx } from 'clsx';
import { ChevronDown } from 'lucide-react';

export interface AccordionProps {
  /**
   * Mode `single` : un seul item ouvert à la fois (utilise l'attribut
   * `name` natif HTML, supporté Chrome 120+, Firefox 122+, Safari 17+).
   * Mode `multiple` : plusieurs items peuvent être ouverts.
   */
  type?: 'single' | 'multiple';
  className?: string;
  children?: ReactNode;
}

/**
 * Accordéon basé sur `<details>` / `<summary>` natifs HTML
 * (cf. décision F.1).
 *
 * A11y native (focus, expand/collapse géré par le navigateur). Le mode
 * `single` utilise l'attribut natif `name` pour rendre les items
 * mutuellement exclusifs.
 */
export function Accordion({ type = 'multiple', className, children }: AccordionProps) {
  const reactId = useId();
  const groupName = type === 'single' ? `pf-accordion-${reactId}` : undefined;

  return (
    <div className={clsx('ori-accordion', className)} data-accordion-name={groupName}>
      {children}
    </div>
  );
}

export interface AccordionItemProps {
  /** Titre cliquable de l'item. */
  title: ReactNode;
  /** Ouvert par défaut. Pour le contrôle dynamique, utiliser plusieurs items. */
  defaultOpen?: boolean;
  className?: string;
  children?: ReactNode;
}

function AccordionItem({ title, defaultOpen, className, children }: AccordionItemProps) {
  // On ne peut pas accéder au context Accordion sans complication ; on lit
  // l'attribut data-* du parent au render. Acceptable parce qu'on n'a pas
  // besoin de réactivité ici (le name est fixé à la création).
  return (
    <details
      className={clsx('ori-accordion__item', className)}
      open={defaultOpen}
      ref={(el) => {
        if (!el) return;
        const groupName = el.parentElement?.getAttribute('data-accordion-name');
        if (groupName) el.setAttribute('name', groupName);
        else el.removeAttribute('name');
      }}
    >
      <summary className="ori-accordion__summary">
        <span>{title}</span>
        <ChevronDown size={18} className="ori-accordion__chevron" aria-hidden="true" />
      </summary>
      <div className="ori-accordion__content">{children}</div>
    </details>
  );
}

Accordion.Item = AccordionItem;
