// packages/react/src/components/DataTable/DataTable.tsx
import { forwardRef, useId, useMemo, useState, type ReactNode } from 'react';
import { clsx } from 'clsx';
import { MoreVertical, Search } from 'lucide-react';
import { Table, type TableColumn, type TableSort, type SortDirection } from '../Table/Table.js';
import { Pagination } from '../Pagination/Pagination.js';
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from '../DropdownMenu/DropdownMenu.js';

/**
 * DataTable : Table + Pagination + filtre global + actions de ligne.
 *
 * Composition au-dessus de Table, Pagination et DropdownMenu. Gère l'état
 * (page courante, filtre, tri) en interne par défaut, ou de façon contrôlée
 * via les props `page` / `onPageChange` / `sort` / `onSortChange` /
 * `globalFilter` / `onGlobalFilterChange` si l'app veut piloter elle-même.
 *
 * Volontairement v1 :
 * - tri sur une seule colonne (pas multi-tri)
 * - filtre global texte uniquement (pas de filtres par colonne)
 * - actions de ligne via DropdownMenu (3-dots) ; pas de checkbox sélection
 *
 * Filtre global : applique un `String(value).toLocaleLowerCase().includes(query)`
 * sur les colonnes marquées `filterable: true`. Override via la prop
 * `filterFn` pour des règles métier (recherche fuzzy, multi-mots, etc.).
 *
 * Tri : par défaut, tri lexicographique sur la valeur retournée par
 * l'accesseur de colonne (`render` ou `row[key]` si pas de render). Override
 * via la prop `sortFn` par colonne dans `extendedColumns`.
 */

export interface DataTableColumn<TRow> extends TableColumn<TRow> {
  /** Si true, cette colonne est incluse dans le filtre global. */
  filterable?: boolean;
  /** Fonction de comparaison custom pour le tri. Default : compare strings. */
  sortFn?: (a: TRow, b: TRow) => number;
}

export interface DataTableRowAction {
  id: string;
  label: ReactNode;
  icon?: ReactNode;
  destructive?: boolean;
  disabled?: boolean;
  /** Insère un séparateur AVANT cet item dans le menu. */
  separatorBefore?: boolean;
}

export interface DataTableProps<TRow> {
  columns: DataTableColumn<TRow>[];
  data: TRow[];
  /** Identifiant unique d'une row (pour les keys et les actions). */
  rowKey: (row: TRow) => string;

  /** Affiche un input de filtre global au-dessus de la table. Default: true. */
  globalFilter?: boolean;
  /** Placeholder de l'input de filtre. */
  filterPlaceholder?: string;
  /** Override de la fonction de filtrage. Default : includes insensible casse. */
  filterFn?: (row: TRow, query: string) => boolean;

  /** Nombre de lignes par page. Default: 10. */
  pageSize?: number;
  /** Désactive la pagination (affiche toutes les lignes). */
  noPagination?: boolean;

  /** Liste d'actions disponibles par ligne (3-dots menu). */
  rowActions?: (row: TRow) => DataTableRowAction[];
  /** Callback déclenché au clic sur une action de ligne. */
  onRowAction?: (action: string, row: TRow) => void;
  /** Label aria-label du bouton 3-dots. */
  rowActionsLabel?: string;

  /** Texte affiché quand aucune ligne ne correspond après filtrage. */
  emptyMessage?: ReactNode;
  /** État de chargement (passé à Table). */
  loading?: boolean;
  /** Caption de la table (pour les SR). */
  caption?: ReactNode;

  className?: string;
}

const defaultFilter = <TRow,>(
  row: TRow,
  query: string,
  filterableKeys: (keyof TRow | string)[],
): boolean => {
  if (!query) return true;
  const q = query.toLocaleLowerCase();
  return filterableKeys.some((key) => {
    const value = (row as Record<string, unknown>)[key as string];
    if (value == null) return false;
    return String(value).toLocaleLowerCase().includes(q);
  });
};

export const DataTable = forwardRef(function DataTable<TRow>(
  {
    columns,
    data,
    rowKey,
    globalFilter = true,
    filterPlaceholder = 'Rechercher…',
    filterFn,
    pageSize = 10,
    noPagination,
    rowActions,
    onRowAction,
    rowActionsLabel = 'Actions',
    emptyMessage = 'Aucune donnée à afficher.',
    loading,
    caption,
    className,
  }: DataTableProps<TRow>,
  ref: React.Ref<HTMLDivElement>,
) {
  const reactId = useId();
  const filterInputId = `pf-data-table-filter-${reactId}`;

  const [query, setQuery] = useState('');
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState<TableSort | undefined>(undefined);

  // Filtrage
  const filterableKeys = useMemo(
    () => columns.filter((c) => c.filterable).map((c) => c.key),
    [columns],
  );
  const effectiveFilter =
    filterFn ?? ((row: TRow, q: string) => defaultFilter(row, q, filterableKeys));

  const filtered = useMemo(() => {
    if (!query) return data;
    return data.filter((row) => effectiveFilter(row, query));
  }, [data, query, effectiveFilter]);

  // Tri
  const sorted = useMemo(() => {
    if (!sort) return filtered;
    const col = columns.find((c) => c.key === sort.column);
    if (!col) return filtered;
    const sortFn = (col as DataTableColumn<TRow>).sortFn;
    const copy = [...filtered];
    copy.sort((a, b) => {
      let cmp: number;
      if (sortFn) {
        cmp = sortFn(a, b);
      } else {
        const aVal = (a as Record<string, unknown>)[col.key];
        const bVal = (b as Record<string, unknown>)[col.key];
        const aStr = aVal == null ? '' : String(aVal);
        const bStr = bVal == null ? '' : String(bVal);
        cmp = aStr.localeCompare(bStr);
      }
      return sort.direction === 'desc' ? -cmp : cmp;
    });
    return copy;
  }, [filtered, sort, columns]);

  // Pagination
  const totalPages = noPagination ? 1 : Math.max(1, Math.ceil(sorted.length / pageSize));
  const clampedPage = Math.min(page, totalPages);
  const paginated = useMemo(() => {
    if (noPagination) return sorted;
    const start = (clampedPage - 1) * pageSize;
    return sorted.slice(start, start + pageSize);
  }, [sorted, clampedPage, pageSize, noPagination]);

  // Reset page si le filtre/tri change et qu'on dépasse le total
  if (clampedPage !== page && totalPages > 0) {
    setPage(clampedPage);
  }

  const handleSortChange = (newSort: TableSort) => {
    // Toggle : asc → desc → off
    if (sort?.column === newSort.column) {
      const next: SortDirection | undefined = sort.direction === 'asc' ? 'desc' : undefined;
      setSort(next ? { column: newSort.column, direction: next } : undefined);
    } else {
      setSort(newSort);
    }
  };

  // Si rowActions fourni, ajoute une colonne d'actions à droite
  const augmentedColumns: TableColumn<TRow>[] = useMemo(() => {
    if (!rowActions) return columns;
    const actionsColumn: TableColumn<TRow> = {
      key: '__actions',
      label: '',
      width: '3rem',
      align: 'end',
      render: (row) => {
        const actions = rowActions(row);
        if (!actions.length) return null;
        return (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button
                type="button"
                className="ori-data-table__row-actions-trigger"
                aria-label={rowActionsLabel}
              >
                <MoreVertical size={16} aria-hidden="true" />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {actions.map((a, idx) => (
                <DataTableActionItem
                  key={a.id}
                  action={a}
                  onSelect={() => onRowAction?.(a.id, row)}
                  separatorBefore={a.separatorBefore && idx > 0}
                />
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        );
      },
    };
    return [...columns, actionsColumn];
  }, [columns, rowActions, onRowAction, rowActionsLabel]);

  return (
    <div ref={ref} className={clsx('ori-data-table', className)}>
      {globalFilter && (
        <div className="ori-data-table__toolbar">
          <label htmlFor={filterInputId} className="ori-data-table__filter-label">
            <span className="ori-data-table__filter-icon" aria-hidden="true">
              <Search size={16} />
            </span>
            <input
              id={filterInputId}
              type="search"
              className="ori-data-table__filter-input"
              placeholder={filterPlaceholder}
              value={query}
              onChange={(e) => {
                setQuery(e.target.value);
                setPage(1);
              }}
            />
          </label>
          <span className="ori-data-table__count" aria-live="polite">
            {sorted.length} résultat{sorted.length > 1 ? 's' : ''}
          </span>
        </div>
      )}
      <Table
        columns={augmentedColumns}
        rows={paginated}
        rowKey={rowKey}
        sort={sort}
        onSortChange={handleSortChange}
        loading={loading}
        emptyMessage={emptyMessage}
        caption={caption}
      />
      {!noPagination && totalPages > 1 && (
        <div className="ori-data-table__footer">
          <Pagination
            page={clampedPage}
            totalPages={totalPages}
            onPageChange={setPage}
            aria-label="Pagination du tableau"
          />
        </div>
      )}
    </div>
  );
}) as <TRow>(
  props: DataTableProps<TRow> & { ref?: React.Ref<HTMLDivElement> },
) => React.ReactElement;

function DataTableActionItem({
  action,
  onSelect,
  separatorBefore,
}: {
  action: DataTableRowAction;
  onSelect: () => void;
  separatorBefore?: boolean;
}) {
  return (
    <>
      {separatorBefore && <DropdownMenuSeparator />}
      <DropdownMenuItem
        icon={action.icon}
        destructive={action.destructive}
        disabled={action.disabled}
        onSelect={onSelect}
      >
        {action.label}
      </DropdownMenuItem>
    </>
  );
}

// packages/angular/src/components/data-table/data-table.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
  ViewChild,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, MoreVertical, Search } from 'lucide-angular';
import {
  OriTableComponent,
  type OriTableColumn,
  type OriTableSort,
} from '../table/table.component';
import { OriPaginationComponent } from '../pagination/pagination.component';
import {
  OriDropdownMenuComponent,
  type OriDropdownMenuItem,
} from '../dropdown-menu/dropdown-menu.component';

type LucideIconData = typeof MoreVertical;

let nextUid = 0;

export interface OriDataTableColumn<TRow = Record<string, unknown>> extends OriTableColumn<TRow> {
  /** Si true, cette colonne est incluse dans le filtre global. */
  filterable?: boolean;
  /** Fonction de comparaison custom pour le tri. Default : compare strings. */
  sortFn?: (a: TRow, b: TRow) => number;
}

export interface OriDataTableRowAction {
  id: string;
  label: string;
  icon?: LucideIconData;
  destructive?: boolean;
  disabled?: boolean;
  /** Insère un séparateur AVANT cet item dans le menu. */
  separatorBefore?: boolean;
}

export interface OriDataTableRowActionEvent<TRow> {
  action: string;
  row: TRow;
}

/**
 * DataTable : Table + Pagination + filtre global + actions de ligne.
 *
 * Composition au-dessus de Table, Pagination et DropdownMenu. Gère l'état
 * (page courante, filtre, tri) en interne. Pour les très grosses tables
 * server-paginées, utiliser directement <ori-table> + <ori-pagination> et
 * piloter pagination/sort/filter côté app.
 *
 * Volontairement v1 :
 * - tri sur une seule colonne (pas multi-tri)
 * - filtre global texte uniquement (pas de filtres par colonne)
 * - actions de ligne via DropdownMenu (3-dots) ; pas de checkbox sélection
 */
@Component({
  selector: 'ori-data-table',
  standalone: true,
  imports: [
    CommonModule,
    LucideAngularModule,
    OriTableComponent,
    OriPaginationComponent,
    OriDropdownMenuComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="ori-data-table">
      @if (globalFilter) {
        <div class="ori-data-table__toolbar">
          <label [attr.for]="filterInputId" class="ori-data-table__filter-label">
            <span class="ori-data-table__filter-icon" aria-hidden="true">
              <lucide-icon [img]="SearchIcon" [size]="16"></lucide-icon>
            </span>
            <input
              [id]="filterInputId"
              type="search"
              class="ori-data-table__filter-input"
              [placeholder]="filterPlaceholder"
              [value]="query"
              (input)="onFilterInput($event)"
            />
          </label>
          <span class="ori-data-table__count" aria-live="polite">
            {{ sortedFiltered.length }} résultat{{ sortedFiltered.length > 1 ? 's' : '' }}
          </span>
        </div>
      }
      <ori-table
        [columns]="augmentedColumns"
        [rows]="paginatedRows"
        [sort]="sort"
        [rowKey]="rowKey"
        [loading]="loading"
        [emptyMessage]="emptyMessage"
        [caption]="caption"
        (sortChange)="onSortChange($event)"
      ></ori-table>
      @if (!noPagination && totalPages > 1) {
        <div class="ori-data-table__footer">
          <ori-pagination
            [page]="clampedPage"
            [totalPages]="totalPages"
            (pageChange)="onPageChange($event)"
            ariaLabel="Pagination du tableau"
          ></ori-pagination>
        </div>
      }
      <ng-template #actionsTpl let-row>
        @if (rowActions) {
          @let actions = rowActions(row);
          @if (actions.length > 0) {
            <ori-dropdown-menu
              [items]="actionsToMenuItems(actions)"
              align="end"
              [ariaLabel]="rowActionsLabel"
              (select)="onMenuSelect($event, row)"
            >
              <button
                type="button"
                slot="trigger"
                class="ori-data-table__row-actions-trigger"
                [attr.aria-label]="rowActionsLabel"
              >
                <lucide-icon [img]="MoreVerticalIcon" [size]="16" aria-hidden="true"></lucide-icon>
              </button>
            </ori-dropdown-menu>
          }
        }
      </ng-template>
    </div>
  `,
})
export class OriDataTableComponent<TRow = Record<string, unknown>> implements AfterViewInit {
  @Input() set columns(value: OriDataTableColumn<TRow>[]) {
    this._columns = value ?? [];
    this.recompute();
  }
  get columns(): OriDataTableColumn<TRow>[] {
    return this._columns;
  }

  @Input() set data(value: TRow[]) {
    this._data = value ?? [];
    this.recompute();
  }
  get data(): TRow[] {
    return this._data;
  }

  @Input() rowKey: ((row: TRow, index: number) => string) | null = null;

  @Input() globalFilter: boolean = true;
  @Input() filterPlaceholder: string = 'Rechercher…';
  @Input() filterFn: ((row: TRow, query: string) => boolean) | null = null;

  @Input() pageSize: number = 10;
  @Input() noPagination: boolean = false;

  @Input() set rowActions(value: ((row: TRow) => OriDataTableRowAction[]) | null) {
    this._rowActions = value;
    this.recompute();
  }
  get rowActions(): ((row: TRow) => OriDataTableRowAction[]) | null {
    return this._rowActions;
  }

  @Input() rowActionsLabel: string = 'Actions';

  @Input() loading: boolean = false;
  @Input() emptyMessage: string = 'Aucune donnée à afficher.';
  @Input() caption: string = '';

  @Output() rowAction = new EventEmitter<OriDataTableRowActionEvent<TRow>>();

  @ViewChild('actionsTpl', { static: false })
  protected actionsTpl?: TemplateRef<{ $implicit: TRow; index: number }>;

  protected readonly SearchIcon: LucideIconData = Search;
  protected readonly MoreVerticalIcon: LucideIconData = MoreVertical;

  protected readonly filterInputId = `pf-data-table-filter-${++nextUid}`;

  protected query: string = '';
  protected page: number = 1;
  protected sort: OriTableSort | null = null;

  protected sortedFiltered: TRow[] = [];
  protected paginatedRows: TRow[] = [];
  protected augmentedColumns: OriTableColumn<TRow>[] = [];

  private _columns: OriDataTableColumn<TRow>[] = [];
  private _data: TRow[] = [];
  private _rowActions: ((row: TRow) => OriDataTableRowAction[]) | null = null;

  private readonly cdr = inject(ChangeDetectorRef);

  ngAfterViewInit(): void {
    // Une fois la TemplateRef disponible, on rebranche les colonnes augmentées
    // pour que la cellule d'actions utilise le template du dropdown.
    this.recompute();
  }

  protected get totalPages(): number {
    if (this.noPagination) return 1;
    return Math.max(1, Math.ceil(this.sortedFiltered.length / this.pageSize));
  }

  protected get clampedPage(): number {
    return Math.min(this.page, this.totalPages);
  }

  protected onFilterInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.query = target.value;
    this.page = 1;
    this.recompute();
  }

  protected onSortChange(newSort: OriTableSort): void {
    if (this.sort && this.sort.column === newSort.column) {
      // Toggle : asc → desc → off
      if (this.sort.direction === 'asc') {
        this.sort = { column: newSort.column, direction: 'desc' };
      } else {
        this.sort = null;
      }
    } else {
      this.sort = newSort;
    }
    this.recompute();
  }

  protected onPageChange(page: number): void {
    this.page = page;
    this.recompute();
  }

  protected onMenuSelect(item: OriDropdownMenuItem, row: TRow): void {
    if (!item.id) return;
    this.rowAction.emit({ action: item.id, row });
  }

  protected actionsToMenuItems(actions: OriDataTableRowAction[]): OriDropdownMenuItem[] {
    const items: OriDropdownMenuItem[] = [];
    actions.forEach((a, idx) => {
      if (a.separatorBefore && idx > 0) {
        items.push({ separator: true });
      }
      items.push({
        id: a.id,
        label: a.label,
        icon: a.icon,
        destructive: a.destructive,
        disabled: a.disabled,
      });
    });
    return items;
  }

  private recompute(): void {
    // Filtrage
    const filterableKeys = this._columns.filter((c) => c.filterable).map((c) => c.key);
    let filtered: TRow[];
    if (!this.query) {
      filtered = this._data.slice();
    } else if (this.filterFn) {
      filtered = this._data.filter((row) => this.filterFn!(row, this.query));
    } else {
      const q = this.query.toLocaleLowerCase();
      filtered = this._data.filter((row) =>
        filterableKeys.some((key) => {
          const value = (row as Record<string, unknown>)[key];
          return value != null && String(value).toLocaleLowerCase().includes(q);
        }),
      );
    }

    // Tri
    if (this.sort) {
      const col = this._columns.find((c) => c.key === this.sort!.column);
      if (col) {
        const direction = this.sort.direction;
        const sortFn = col.sortFn;
        filtered = filtered.slice().sort((a, b) => {
          let cmp: number;
          if (sortFn) {
            cmp = sortFn(a, b);
          } else {
            const aVal = (a as Record<string, unknown>)[col.key];
            const bVal = (b as Record<string, unknown>)[col.key];
            const aStr = aVal == null ? '' : String(aVal);
            const bStr = bVal == null ? '' : String(bVal);
            cmp = aStr.localeCompare(bStr);
          }
          return direction === 'desc' ? -cmp : cmp;
        });
      }
    }

    this.sortedFiltered = filtered;

    // Pagination
    if (this.noPagination) {
      this.paginatedRows = filtered;
    } else {
      const start = (this.clampedPage - 1) * this.pageSize;
      this.paginatedRows = filtered.slice(start, start + this.pageSize);
    }

    // Colonnes augmentées : ajout d'une colonne actions si rowActions fourni,
    // utilisant la TemplateRef interne actionsTpl pour rendre le DropdownMenu.
    if (this._rowActions) {
      this.augmentedColumns = [
        ...this._columns,
        {
          key: '__actions',
          label: '',
          width: '3rem',
          align: 'end',
          cellTemplate: this.actionsTpl,
        },
      ];
    } else {
      this.augmentedColumns = this._columns.slice();
    }

    this.cdr.markForCheck();
  }
}
