// packages/angular/src/components/tag/tag.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import { LucideAngularModule, X } from 'lucide-angular';

type LucideIconData = typeof X;

export type OriTagVariant = 'neutral' | 'info' | 'success' | 'warning' | 'danger';

@Component({
  selector: 'ori-tag',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <span [class]="tagClasses">
      <ng-content></ng-content>
      @if (removable) {
        <button
          type="button"
          class="ori-tag__remove"
          [attr.aria-label]="removeLabel"
          (click)="remove.emit($event)"
        >
          <lucide-icon [img]="XIcon" [size]="12" aria-hidden="true"></lucide-icon>
        </button>
      }
    </span>
  `,
})
export class OriTagComponent {
  @Input() variant: OriTagVariant = 'neutral';
  /** Affiche un bouton de suppression à droite. */
  @Input() removable: boolean = false;
  @Input() removeLabel: string = 'Retirer';

  @Output() remove = new EventEmitter<MouseEvent>();

  protected readonly XIcon: LucideIconData = X;

  get tagClasses(): string {
    return `ori-tag ori-tag--${this.variant}`;
  }
}

// packages/react/src/components/Tag/Tag.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';
import { X } from 'lucide-react';

export type TagVariant = 'neutral' | 'info' | 'success' | 'warning' | 'danger';

export interface TagProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'onRemove'> {
  variant?: TagVariant;
  /**
   * Si défini, affiche un bouton de suppression à droite. La callback
   * reçoit l'événement click pour permettre `stopPropagation()` si le
   * Tag est dans un container cliquable.
   */
  onRemove?: (event: React.MouseEvent<HTMLButtonElement>) => void;
  /** Étiquette ARIA du bouton de suppression. */
  removeLabel?: string;
  children?: ReactNode;
}

/**
 * Tag (badge) pour afficher un état, une catégorie ou un filtre actif.
 * 5 variantes sémantiques. Optionnellement supprimable.
 */
export function Tag({
  variant = 'neutral',
  onRemove,
  removeLabel = 'Retirer',
  className,
  children,
  ...rest
}: TagProps) {
  return (
    <span className={clsx('ori-tag', `ori-tag--${variant}`, className)} {...rest}>
      {children}
      {onRemove && (
        <button
          type="button"
          className="ori-tag__remove"
          onClick={onRemove}
          aria-label={removeLabel}
        >
          <X size={12} aria-hidden="true" />
        </button>
      )}
    </span>
  );
}
