// packages/react/src/components/LanguageSwitcher/LanguageSwitcher.tsx
import { useEffect, useRef, useState, type HTMLAttributes } from 'react';
import { clsx } from 'clsx';
import { Globe, ChevronDown } from 'lucide-react';

export interface LanguageOption {
  /** Code ISO 639 (ex: 'fr', 'en', 'ty'). */
  code: string;
  /** Libellé d'affichage dans la liste (ex: 'Français', 'Reo Tahiti'). */
  label: string;
}

export interface LanguageSwitcherProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  /** Langues disponibles. Cf. décision J.2 : fournies par l'app. */
  languages: LanguageOption[];
  /** Code de la langue active. */
  value: string;
  /** Callback de changement. */
  onChange: (code: string) => void;
  /** Étiquette ARIA du bouton (lecteur d'écran). */
  triggerAriaLabel?: string;
}

/**
 * Sélecteur de langue compact pour header (cf. décision J.2).
 * Liste de langues fournie par l'app, pas de hardcoding.
 */
export function LanguageSwitcher({
  languages,
  value,
  onChange,
  triggerAriaLabel = 'Changer la langue',
  className,
  ...rest
}: LanguageSwitcherProps) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);

  // Fermeture au clic extérieur
  useEffect(() => {
    if (!open) return;
    const onDocClick = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', onDocClick);
    return () => document.removeEventListener('mousedown', onDocClick);
  }, [open]);

  // Fermeture sur Escape
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open]);

  const select = (code: string) => {
    onChange(code);
    setOpen(false);
  };

  return (
    <div ref={wrapRef} className={clsx('ori-language-switcher', className)} {...rest}>
      <button
        type="button"
        className="ori-language-switcher__trigger"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label={triggerAriaLabel}
        onClick={() => setOpen((o) => !o)}
      >
        <Globe size={14} aria-hidden="true" />
        {value}
        <ChevronDown size={14} aria-hidden="true" />
      </button>
      {open && (
        <ul role="listbox" className="ori-language-switcher__menu">
          {languages.map((lang) => (
            <li key={lang.code} role="presentation">
              <button
                type="button"
                role="option"
                className="ori-language-switcher__option"
                aria-checked={lang.code === value}
                onClick={() => select(lang.code)}
              >
                {lang.label}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// packages/angular/src/components/language-switcher/language-switcher.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { LucideAngularModule, Globe, ChevronDown } from 'lucide-angular';

type LucideIconData = typeof Globe;

export interface OriLanguageOption {
  code: string;
  label: string;
}

/**
 * Sélecteur de langue compact (cf. décision J.2).
 * Liste de langues fournie par l'app, pas de hardcoding.
 */
@Component({
  selector: 'ori-language-switcher',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="ori-language-switcher">
      <button
        type="button"
        class="ori-language-switcher__trigger"
        aria-haspopup="listbox"
        [attr.aria-expanded]="open"
        [attr.aria-label]="triggerAriaLabel"
        (click)="toggle()"
      >
        <lucide-icon [img]="GlobeIcon" [size]="14" aria-hidden="true"></lucide-icon>
        {{ value }}
        <lucide-icon [img]="ChevronDownIcon" [size]="14" aria-hidden="true"></lucide-icon>
      </button>
      @if (open) {
        <ul role="listbox" class="ori-language-switcher__menu">
          @for (lang of languages; track lang.code) {
            <li role="presentation">
              <button
                type="button"
                role="option"
                class="ori-language-switcher__option"
                [attr.aria-checked]="lang.code === value"
                (click)="select(lang.code)"
              >
                {{ lang.label }}
              </button>
            </li>
          }
        </ul>
      }
    </div>
  `,
})
export class OriLanguageSwitcherComponent {
  @Input() languages: OriLanguageOption[] = [];
  @Input() value: string = '';
  @Input() triggerAriaLabel: string = 'Changer la langue';

  @Output() languageChange = new EventEmitter<string>();

  open = false;

  protected readonly GlobeIcon: LucideIconData = Globe;
  protected readonly ChevronDownIcon: LucideIconData = ChevronDown;

  private readonly host = inject(ElementRef<HTMLElement>);

  toggle(): void {
    this.open = !this.open;
  }

  select(code: string): void {
    this.languageChange.emit(code);
    this.open = false;
  }

  @HostListener('document:click', ['$event'])
  onDocClick(event: MouseEvent): void {
    if (!this.open) return;
    if (!this.host.nativeElement.contains(event.target as Node)) {
      this.open = false;
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    this.open = false;
  }
}
