// packages/angular/src/components/wizard/wizard.component.ts
import {
  AfterContentInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChildren,
  EventEmitter,
  Input,
  Output,
  QueryList,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { OriStepsComponent, type OriStepItem } from '../steps/steps.component';
import { OriButtonComponent } from '../button/button.component';

let nextUid = 0;

/**
 * Étape déclarative d'un Wizard. Doit être enfant direct d'<ori-wizard>.
 *
 * L'étape rend son contenu (`ng-content`) en permanence dans le DOM mais
 * masquée via `[hidden]` quand non active. Ça évite de réinitialiser les
 * formulaires Reactive Forms à chaque changement d'étape (perte de saisie),
 * tout en gardant l'a11y propre (l'élément non actif n'apparaît pas à l'AT).
 */
@Component({
  selector: 'ori-wizard-step',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [hidden]="!active" class="ori-wizard__step-body">
      <ng-content></ng-content>
    </div>
  `,
})
export class OriWizardStepComponent {
  @Input() title: string = '';
  @Input() description: string = '';

  /** Activé par le parent <ori-wizard> via le query ContentChildren. */
  active: boolean = false;

  private readonly cdr = inject(ChangeDetectorRef);

  setActive(active: boolean): void {
    if (this.active === active) return;
    this.active = active;
    this.cdr.markForCheck();
  }
}

/**
 * Wizard multi-étapes.
 *
 * Assemble Steps + contenu actif + actions Précédent / Suivant / Soumettre.
 * Chaque étape est déclarée via un <ori-wizard-step> enfant.
 *
 * Validation : Ori ne pose aucune logique. L'app gère côté Reactive Forms /
 * signals et désactive l'avancement via `[canProceed]="false"`.
 *
 * Parité avec la version React : même API publique (currentStep,
 * canProceed, onComplete, allowGoBack), mêmes labels par défaut.
 */
@Component({
  selector: 'ori-wizard',
  standalone: true,
  imports: [OriStepsComponent, OriButtonComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="ori-wizard">
      <ori-steps
        class="ori-wizard__steps"
        [steps]="stepItems"
        [current]="clampedCurrent"
        [clickable]="allowGoBack"
        (stepClick)="onStepClick($event)"
      ></ori-steps>
      <section class="ori-wizard__panel" [attr.aria-labelledby]="titleId">
        <h2 [id]="titleId" class="ori-wizard__step-title">{{ activeStepTitle }}</h2>
        <ng-content></ng-content>
      </section>
      <div class="ori-wizard__actions">
        <ori-button variant="secondary" [disabled]="isFirst" (click)="goToPrevious()">
          {{ previousLabel }}
        </ori-button>
        @if (isLast) {
          <ori-button [disabled]="!canProceed" (click)="handleSubmit()">{{
            submitLabel
          }}</ori-button>
        } @else {
          <ori-button [disabled]="!canProceed" (click)="goToNext()">{{ nextLabel }}</ori-button>
        }
      </div>
    </div>
  `,
})
export class OriWizardComponent implements AfterContentInit {
  @Input() set currentStep(value: number) {
    this._currentStep = value;
    this.refreshActive();
  }
  get currentStep(): number {
    return this._currentStep;
  }

  @Input() canProceed: boolean = true;
  @Input() allowGoBack: boolean = true;
  @Input() previousLabel: string = 'Précédent';
  @Input() nextLabel: string = 'Suivant';
  @Input() submitLabel: string = 'Soumettre';

  @Output() stepChange = new EventEmitter<number>();
  @Output() complete = new EventEmitter<void>();

  @ContentChildren(OriWizardStepComponent)
  protected stepsRef?: QueryList<OriWizardStepComponent>;

  protected readonly titleId = `pf-wizard-title-${++nextUid}`;
  protected stepItems: OriStepItem[] = [];
  protected activeStepTitle: string = '';
  protected clampedCurrent: number = 0;
  protected isFirst: boolean = true;
  protected isLast: boolean = false;

  private _currentStep: number = 0;

  private readonly cdr = inject(ChangeDetectorRef);

  ngAfterContentInit(): void {
    this.refreshActive();
    this.stepsRef?.changes.subscribe(() => this.refreshActive());
  }

  protected onStepClick(index: number): void {
    if (!this.allowGoBack) return;
    this.stepChange.emit(index);
  }

  protected goToPrevious(): void {
    if (!this.isFirst) this.stepChange.emit(this.clampedCurrent - 1);
  }

  protected goToNext(): void {
    if (!this.isLast && this.canProceed) this.stepChange.emit(this.clampedCurrent + 1);
  }

  protected handleSubmit(): void {
    if (this.canProceed) this.complete.emit();
  }

  private refreshActive(): void {
    if (!this.stepsRef) return;
    const total = this.stepsRef.length;
    if (total === 0) {
      throw new Error('OriWizard doit contenir au moins un <ori-wizard-step>.');
    }
    this.clampedCurrent = Math.max(0, Math.min(this._currentStep, total - 1));
    this.isFirst = this.clampedCurrent === 0;
    this.isLast = this.clampedCurrent === total - 1;
    this.stepItems = this.stepsRef.toArray().map((s) => ({
      title: s.title,
      description: s.description || undefined,
    }));
    this.activeStepTitle = this.stepItems[this.clampedCurrent]?.title ?? '';
    this.stepsRef.forEach((step, idx) => step.setActive(idx === this.clampedCurrent));
    this.cdr.markForCheck();
  }
}

// packages/react/src/components/Wizard/Wizard.tsx
import { Children, forwardRef, isValidElement, type ReactElement, type ReactNode } from 'react';
import { clsx } from 'clsx';
import { Steps, type StepItem } from '../Steps/Steps.js';
import { Button } from '../Button/Button.js';

/**
 * Wizard multi-étapes.
 *
 * Assemble Steps + contenu actif + actions Précédent / Suivant / Soumettre.
 * Chaque étape est déclarée via un <WizardStep> enfant qui porte un titre,
 * une description optionnelle, et son contenu (typiquement un <Form>).
 *
 * Validation : Ori ne pose aucune logique de validation. L'app la gère
 * elle-même et désactive l'avancement via `canProceed` (boolean prop sur
 * <Wizard>) quand l'étape courante n'est pas valide.
 *
 * Pas de skip / step direct par défaut : l'utilisateur peut revenir aux
 * étapes complétées via Steps `clickable` activable côté props.
 *
 * a11y :
 * - Steps porte aria-current="step" sur l'étape courante (cf. composant Steps)
 * - chaque WizardStep est rendu dans un <section> avec aria-labelledby
 *   pointant sur son titre
 * - les boutons d'action sont des `<button>` standard
 */

export interface WizardStepProps {
  /** Titre court de l'étape, affiché dans Steps et en h2 du contenu. */
  title: string;
  /** Description courte optionnelle (Steps). */
  description?: string;
  children?: ReactNode;
}

/**
 * Marqueur déclaratif d'une étape de Wizard. Doit être un enfant direct
 * de <Wizard>. Le rendu effectif est piloté par le parent.
 */
export function WizardStep(_props: WizardStepProps): null {
  return null;
}
WizardStep.displayName = 'WizardStep';

export interface WizardProps {
  /** Index 0-based de l'étape courante (contrôlé). */
  currentStep: number;
  onStepChange?: (index: number) => void;
  /** Si false, le bouton Suivant est désactivé. Default: true. */
  canProceed?: boolean;
  /** Callback déclenché au clic sur Soumettre (sur la dernière étape). */
  onComplete?: () => void;
  /** Permet de re-cliquer sur une étape déjà complétée pour y revenir. Default: true. */
  allowGoBack?: boolean;
  /** Labels des boutons (i18n). */
  previousLabel?: string;
  nextLabel?: string;
  submitLabel?: string;
  children: ReactNode;
  className?: string;
}

export const Wizard = forwardRef<HTMLDivElement, WizardProps>(function Wizard(
  {
    currentStep,
    onStepChange,
    canProceed = true,
    onComplete,
    allowGoBack = true,
    previousLabel = 'Précédent',
    nextLabel = 'Suivant',
    submitLabel = 'Soumettre',
    children,
    className,
  },
  ref,
) {
  // Collecte des étapes via Children + filtrage des WizardStep
  const stepElements = Children.toArray(children).filter(
    (child): child is ReactElement<WizardStepProps> =>
      isValidElement(child) &&
      // @ts-expect-error - displayName peut ne pas être typé
      (child.type === WizardStep || child.type?.displayName === 'WizardStep'),
  );

  if (stepElements.length === 0) {
    throw new Error('Wizard doit contenir au moins un <WizardStep>.');
  }

  const clampedCurrent = Math.max(0, Math.min(currentStep, stepElements.length - 1));
  const isFirst = clampedCurrent === 0;
  const isLast = clampedCurrent === stepElements.length - 1;
  const activeStep = stepElements[clampedCurrent];
  // stepElements.length > 0 garanti par le throw plus haut, donc activeStep est défini.
  if (!activeStep) {
    throw new Error('Wizard : index courant hors limites.');
  }

  const stepsItems: StepItem[] = stepElements.map((el) => ({
    title: el.props.title,
    description: el.props.description,
  }));

  const goToPrevious = () => {
    if (!isFirst) onStepChange?.(clampedCurrent - 1);
  };

  const goToNext = () => {
    if (!isLast && canProceed) onStepChange?.(clampedCurrent + 1);
  };

  const handleSubmit = () => {
    if (canProceed) onComplete?.();
  };

  // Garantir un id stable pour l'aria-labelledby de chaque section
  const baseId = 'pf-wizard';

  return (
    <div ref={ref} className={clsx('ori-wizard', className)}>
      <Steps
        steps={stepsItems}
        current={clampedCurrent}
        clickable={allowGoBack}
        onStepClick={(index) => onStepChange?.(index)}
        className="ori-wizard__steps"
      />
      <section
        className="ori-wizard__panel"
        aria-labelledby={`${baseId}-step-title-${clampedCurrent}`}
      >
        <h2 id={`${baseId}-step-title-${clampedCurrent}`} className="ori-wizard__step-title">
          {activeStep.props.title}
        </h2>
        <div className="ori-wizard__step-body">{activeStep.props.children}</div>
      </section>
      <div className="ori-wizard__actions">
        <Button variant="secondary" onClick={goToPrevious} disabled={isFirst}>
          {previousLabel}
        </Button>
        {isLast ? (
          <Button onClick={handleSubmit} disabled={!canProceed}>
            {submitLabel}
          </Button>
        ) : (
          <Button onClick={goToNext} disabled={!canProceed}>
            {nextLabel}
          </Button>
        )}
      </div>
    </div>
  );
});
