// packages/react/src/components/Combobox/Combobox.tsx
import { forwardRef, useCallback, useEffect, useId, useMemo, useRef, useState } from 'react';
import type { KeyboardEvent } from 'react';
import { clsx } from 'clsx';
import { ChevronDown, Check } from 'lucide-react';

/**
 * Combobox / Autocomplete accessible.
 *
 * Pattern WAI-ARIA "combobox" v1.2 (input texte + listbox externe). Filtre
 * les options à la frappe ; navigation clavier complète ; sélection à
 * l'Entrée ou au clic ; ESC ferme la liste.
 *
 * a11y :
 * - input avec role="combobox", aria-autocomplete="list", aria-expanded,
 *   aria-controls (le listbox), aria-activedescendant (l'option active)
 * - listbox avec role="listbox" + aria-label
 * - chaque option avec role="option" + aria-selected
 *
 * Volontairement pas de multi-select (cf. MultiSelect virtualisé), pas de
 * création d'option à la volée, pas de chargement async (à ouvrir comme
 * extensions si le besoin se confirme côté apps).
 *
 * Volontairement pas basé sur Radix : il n'existe pas (encore) de
 * `@radix-ui/react-combobox` stable. Implémentation custom légère, en parité
 * fonctionnelle avec la version Angular.
 */

export interface ComboboxOption {
  id: string;
  label: string;
  /** Description courte affichée en seconde ligne, optionnelle. */
  description?: string;
  disabled?: boolean;
}

export interface ComboboxProps {
  /** Liste complète des options (filtrée à la frappe par le composant). */
  options: ComboboxOption[];
  /** ID de l'option sélectionnée. */
  value?: string;
  onValueChange?: (id: string | undefined) => void;
  /** Texte du label associé à l'input. Requis pour l'a11y. */
  label: string;
  placeholder?: string;
  disabled?: boolean;
  /** Fonction de filtrage custom. Default : prefix-match insensible à la casse. */
  filterFn?: (option: ComboboxOption, query: string) => boolean;
  /** Texte affiché quand aucune option ne correspond. */
  noResultsLabel?: string;
  className?: string;
}

const defaultFilter = (option: ComboboxOption, query: string): boolean => {
  if (!query) return true;
  const q = query.toLocaleLowerCase();
  return option.label.toLocaleLowerCase().includes(q);
};

export const Combobox = forwardRef<HTMLInputElement, ComboboxProps>(function Combobox(
  {
    options,
    value,
    onValueChange,
    label,
    placeholder,
    disabled,
    filterFn = defaultFilter,
    noResultsLabel = 'Aucun résultat',
    className,
  },
  ref,
) {
  const reactId = useId();
  const inputId = `pf-combobox-input-${reactId}`;
  const listboxId = `pf-combobox-listbox-${reactId}`;
  const labelId = `pf-combobox-label-${reactId}`;

  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [activeIndex, setActiveIndex] = useState(-1);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const selectedOption = useMemo(() => options.find((o) => o.id === value), [options, value]);

  // Quand la valeur change depuis l'extérieur, on resync le query affiché.
  useEffect(() => {
    if (selectedOption && !open) setQuery(selectedOption.label);
    if (!selectedOption && !open && value === undefined) setQuery('');
  }, [selectedOption, open, value]);

  const filtered = useMemo(() => {
    // Si la query correspond exactement au label sélectionné, on n'applique
    // pas de filtre (sinon l'utilisateur ne voit qu'une option et perd le
    // choix de revenir en arrière).
    if (selectedOption && query === selectedOption.label) return options;
    return options.filter((o) => filterFn(o, query));
  }, [options, query, filterFn, selectedOption]);

  const enabledFiltered = useMemo(() => filtered.filter((o) => !o.disabled), [filtered]);

  const closeList = useCallback(() => {
    setOpen(false);
    setActiveIndex(-1);
  }, []);

  const selectOption = useCallback(
    (option: ComboboxOption) => {
      if (option.disabled) return;
      onValueChange?.(option.id);
      setQuery(option.label);
      closeList();
    },
    [onValueChange, closeList],
  );

  const onInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setQuery(e.target.value);
    setOpen(true);
    setActiveIndex(0);
    // Si l'utilisateur efface, on désélectionne.
    if (!e.target.value && value !== undefined) onValueChange?.(undefined);
  };

  const onKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        if (!open) {
          setOpen(true);
          setActiveIndex(0);
        } else if (enabledFiltered.length) {
          setActiveIndex((i) => (i + 1) % enabledFiltered.length);
        }
        break;
      case 'ArrowUp':
        e.preventDefault();
        if (!open) {
          setOpen(true);
          setActiveIndex(enabledFiltered.length - 1);
        } else if (enabledFiltered.length) {
          setActiveIndex((i) => (i <= 0 ? enabledFiltered.length - 1 : i - 1));
        }
        break;
      case 'Home':
        if (open) {
          e.preventDefault();
          setActiveIndex(0);
        }
        break;
      case 'End':
        if (open) {
          e.preventDefault();
          setActiveIndex(enabledFiltered.length - 1);
        }
        break;
      case 'Enter':
        if (open && activeIndex >= 0 && enabledFiltered[activeIndex]) {
          e.preventDefault();
          selectOption(enabledFiltered[activeIndex]);
        }
        break;
      case 'Escape':
        if (open) {
          e.preventDefault();
          closeList();
          // Revenir à la valeur précédente
          setQuery(selectedOption?.label ?? '');
        }
        break;
      case 'Tab':
        // Tab valide la première option si la liste est ouverte avec une
        // valeur active, sinon laisse passer normalement.
        if (open && activeIndex >= 0 && enabledFiltered[activeIndex]) {
          selectOption(enabledFiltered[activeIndex]);
        }
        break;
    }
  };

  // Click outside : ferme et restore la valeur affichée.
  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      if (wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        closeList();
        setQuery(selectedOption?.label ?? '');
      }
    };
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, [open, selectedOption, closeList]);

  // ID de l'option active pour aria-activedescendant
  const activeOptionId =
    open && activeIndex >= 0 && enabledFiltered[activeIndex]
      ? `${listboxId}-option-${enabledFiltered[activeIndex].id}`
      : undefined;

  return (
    <div ref={wrapperRef} className={clsx('ori-combobox', className)}>
      <label id={labelId} htmlFor={inputId} className="ori-combobox__label">
        {label}
      </label>
      <div className="ori-combobox__field">
        <input
          ref={ref}
          id={inputId}
          type="text"
          role="combobox"
          aria-autocomplete="list"
          aria-expanded={open}
          aria-controls={listboxId}
          aria-activedescendant={activeOptionId}
          aria-labelledby={labelId}
          autoComplete="off"
          spellCheck={false}
          disabled={disabled}
          placeholder={placeholder}
          value={query}
          onChange={onInputChange}
          onFocus={() => setOpen(true)}
          onClick={() => setOpen(true)}
          onKeyDown={onKeyDown}
          className="ori-combobox__input"
        />
        <span className="ori-combobox__chevron" aria-hidden="true">
          <ChevronDown size={16} />
        </span>
      </div>
      {open && (
        <ul id={listboxId} role="listbox" aria-label={label} className="ori-combobox__listbox">
          {filtered.length === 0 ? (
            <li className="ori-combobox__empty" aria-disabled="true">
              {noResultsLabel}
            </li>
          ) : (
            filtered.map((option) => {
              // Index dans enabledFiltered pour le calcul de l'option active
              const enabledIndex = option.disabled ? -1 : enabledFiltered.indexOf(option);
              const isActive = enabledIndex === activeIndex;
              const isSelected = option.id === value;
              return (
                <li
                  key={option.id}
                  id={`${listboxId}-option-${option.id}`}
                  role="option"
                  aria-selected={isSelected}
                  aria-disabled={option.disabled || undefined}
                  className={clsx(
                    'ori-combobox__option',
                    isActive && 'ori-combobox__option--active',
                    isSelected && 'ori-combobox__option--selected',
                    option.disabled && 'ori-combobox__option--disabled',
                  )}
                  onMouseDown={(e) => {
                    // Empêche le blur de l'input au mousedown
                    e.preventDefault();
                  }}
                  onClick={() => selectOption(option)}
                  onMouseEnter={() => {
                    if (!option.disabled) setActiveIndex(enabledIndex);
                  }}
                >
                  <span className="ori-combobox__option-text">
                    <span className="ori-combobox__option-label">{option.label}</span>
                    {option.description && (
                      <span className="ori-combobox__option-description">{option.description}</span>
                    )}
                  </span>
                  {isSelected && (
                    <Check size={16} className="ori-combobox__option-check" aria-hidden="true" />
                  )}
                </li>
              );
            })
          )}
        </ul>
      )}
    </div>
  );
});

// packages/angular/src/components/combobox/combobox.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  ViewChild,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { LucideAngularModule, ChevronDown, Check } from 'lucide-angular';

// LucideIconData n'est pas exporté par le barrel public ; on le dérive depuis
// une icône connue pour éviter TS2742 en mode partial-compilation.
type LucideIconData = typeof ChevronDown;

let nextUid = 0;

export interface OriComboboxOption {
  id: string;
  label: string;
  /** Description courte affichée en seconde ligne, optionnelle. */
  description?: string;
  disabled?: boolean;
}

/**
 * Combobox / Autocomplete accessible.
 *
 * Pattern WAI-ARIA "combobox" v1.2 (input texte + listbox externe). Filtre
 * les options à la frappe ; navigation clavier complète ; sélection à
 * l'Entrée ou au clic ; ESC ferme la liste.
 *
 * a11y :
 * - input avec role="combobox", aria-autocomplete="list", aria-expanded,
 *   aria-controls, aria-activedescendant
 * - listbox avec role="listbox" + aria-label
 * - chaque option avec role="option" + aria-selected
 *
 * Volontairement pas de multi-select, pas de chargement async, pas de
 * création d'option à la volée. Parité fonctionnelle avec la version React.
 */
@Component({
  selector: 'ori-combobox',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="ori-combobox">
      <label [id]="labelId" [attr.for]="inputId" class="ori-combobox__label">{{ label }}</label>
      <div class="ori-combobox__field">
        <input
          #input
          [id]="inputId"
          type="text"
          role="combobox"
          aria-autocomplete="list"
          [attr.aria-expanded]="open"
          [attr.aria-controls]="listboxId"
          [attr.aria-activedescendant]="activeOptionId"
          [attr.aria-labelledby]="labelId"
          autocomplete="off"
          spellcheck="false"
          [disabled]="disabled"
          [placeholder]="placeholder"
          [value]="query"
          (input)="onInput($event)"
          (focus)="setOpen(true)"
          (click)="setOpen(true)"
          (keydown)="onKeyDown($event)"
          class="ori-combobox__input"
        />
        <span class="ori-combobox__chevron" aria-hidden="true">
          <lucide-icon [img]="ChevronDownIcon" [size]="16"></lucide-icon>
        </span>
      </div>
      @if (open) {
        <ul [id]="listboxId" role="listbox" [attr.aria-label]="label" class="ori-combobox__listbox">
          @if (filtered.length === 0) {
            <li class="ori-combobox__empty" aria-disabled="true">{{ noResultsLabel }}</li>
          } @else {
            @for (option of filtered; track option.id; let i = $index) {
              <li
                [id]="optionId(option)"
                role="option"
                [attr.aria-selected]="option.id === value"
                [attr.aria-disabled]="option.disabled || null"
                [class.ori-combobox__option]="true"
                [class.ori-combobox__option--active]="enabledIndexOf(option) === activeIndex"
                [class.ori-combobox__option--selected]="option.id === value"
                [class.ori-combobox__option--disabled]="option.disabled"
                (mousedown)="$event.preventDefault()"
                (click)="selectOption(option)"
                (mouseenter)="setActive(option)"
              >
                <span class="ori-combobox__option-text">
                  <span class="ori-combobox__option-label">{{ option.label }}</span>
                  @if (option.description) {
                    <span class="ori-combobox__option-description">{{ option.description }}</span>
                  }
                </span>
                @if (option.id === value) {
                  <lucide-icon
                    class="ori-combobox__option-check"
                    [img]="CheckIcon"
                    [size]="16"
                    aria-hidden="true"
                  ></lucide-icon>
                }
              </li>
            }
          }
        </ul>
      }
    </div>
  `,
})
export class OriComboboxComponent {
  @Input() set options(value: OriComboboxOption[]) {
    this._options = value ?? [];
    this.recompute();
  }
  get options(): OriComboboxOption[] {
    return this._options;
  }

  @Input() set value(v: string | undefined) {
    this._value = v;
    if (!this.open) {
      const opt = this._options.find((o) => o.id === v);
      this.query = opt?.label ?? '';
    }
    this.recompute();
  }
  get value(): string | undefined {
    return this._value;
  }

  @Input() label: string = '';
  @Input() placeholder: string = '';
  @Input() disabled: boolean = false;
  @Input() noResultsLabel: string = 'Aucun résultat';
  /** Fonction de filtrage custom. Default : prefix-match insensible à la casse. */
  @Input() filterFn: (option: OriComboboxOption, query: string) => boolean = (option, q) => {
    if (!q) return true;
    return option.label.toLocaleLowerCase().includes(q.toLocaleLowerCase());
  };

  @Output() valueChange = new EventEmitter<string | undefined>();

  @ViewChild('input') protected inputRef?: ElementRef<HTMLInputElement>;

  protected readonly ChevronDownIcon: LucideIconData = ChevronDown;
  protected readonly CheckIcon: LucideIconData = Check;

  private readonly uid = ++nextUid;
  protected readonly inputId = `pf-combobox-input-${this.uid}`;
  protected readonly listboxId = `pf-combobox-listbox-${this.uid}`;
  protected readonly labelId = `pf-combobox-label-${this.uid}`;

  protected open = false;
  protected query = '';
  protected activeIndex = -1;
  protected filtered: OriComboboxOption[] = [];
  protected enabledFiltered: OriComboboxOption[] = [];

  private _options: OriComboboxOption[] = [];
  private _value: string | undefined;

  private readonly cdr = inject(ChangeDetectorRef);
  private readonly hostRef = inject(ElementRef<HTMLElement>);

  protected get activeOptionId(): string | null {
    if (!this.open || this.activeIndex < 0) return null;
    const opt = this.enabledFiltered[this.activeIndex];
    return opt ? this.optionId(opt) : null;
  }

  protected optionId(option: OriComboboxOption): string {
    return `${this.listboxId}-option-${option.id}`;
  }

  protected enabledIndexOf(option: OriComboboxOption): number {
    return this.enabledFiltered.indexOf(option);
  }

  protected setOpen(open: boolean): void {
    if (this.open === open) return;
    this.open = open;
    if (open && this.activeIndex < 0) this.activeIndex = 0;
    this.recompute();
  }

  protected setActive(option: OriComboboxOption): void {
    if (option.disabled) return;
    const idx = this.enabledFiltered.indexOf(option);
    if (idx >= 0 && idx !== this.activeIndex) {
      this.activeIndex = idx;
      this.cdr.markForCheck();
    }
  }

  protected onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.query = target.value;
    this.open = true;
    this.activeIndex = 0;
    if (!target.value && this._value !== undefined) {
      this._value = undefined;
      this.valueChange.emit(undefined);
    }
    this.recompute();
  }

  protected selectOption(option: OriComboboxOption): void {
    if (option.disabled) return;
    this._value = option.id;
    this.query = option.label;
    this.valueChange.emit(option.id);
    this.closeList();
  }

  protected onKeyDown(event: KeyboardEvent): void {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (!this.open) {
          this.open = true;
          this.activeIndex = 0;
          this.recompute();
        } else if (this.enabledFiltered.length) {
          this.activeIndex = (this.activeIndex + 1) % this.enabledFiltered.length;
          this.cdr.markForCheck();
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (!this.open) {
          this.open = true;
          this.activeIndex = this.enabledFiltered.length - 1;
          this.recompute();
        } else if (this.enabledFiltered.length) {
          this.activeIndex =
            this.activeIndex <= 0 ? this.enabledFiltered.length - 1 : this.activeIndex - 1;
          this.cdr.markForCheck();
        }
        break;
      case 'Home':
        if (this.open) {
          event.preventDefault();
          this.activeIndex = 0;
          this.cdr.markForCheck();
        }
        break;
      case 'End':
        if (this.open) {
          event.preventDefault();
          this.activeIndex = this.enabledFiltered.length - 1;
          this.cdr.markForCheck();
        }
        break;
      case 'Enter':
        if (this.open && this.activeIndex >= 0 && this.enabledFiltered[this.activeIndex]) {
          event.preventDefault();
          this.selectOption(this.enabledFiltered[this.activeIndex]);
        }
        break;
      case 'Escape':
        if (this.open) {
          event.preventDefault();
          this.closeList();
          // Restaurer le label de la valeur actuelle
          const opt = this._options.find((o) => o.id === this._value);
          this.query = opt?.label ?? '';
          this.cdr.markForCheck();
        }
        break;
      case 'Tab':
        if (this.open && this.activeIndex >= 0 && this.enabledFiltered[this.activeIndex]) {
          this.selectOption(this.enabledFiltered[this.activeIndex]);
        }
        break;
    }
  }

  @HostListener('document:mousedown', ['$event'])
  protected onDocumentMouseDown(event: MouseEvent): void {
    if (!this.open) return;
    const target = event.target as Node;
    if (!this.hostRef.nativeElement.contains(target)) {
      this.closeList();
      const opt = this._options.find((o) => o.id === this._value);
      this.query = opt?.label ?? '';
      this.cdr.markForCheck();
    }
  }

  private closeList(): void {
    this.open = false;
    this.activeIndex = -1;
    this.cdr.markForCheck();
  }

  private recompute(): void {
    const selected = this._options.find((o) => o.id === this._value);
    if (selected && this.query === selected.label) {
      this.filtered = this._options.slice();
    } else {
      this.filtered = this._options.filter((o) => this.filterFn(o, this.query));
    }
    this.enabledFiltered = this.filtered.filter((o) => !o.disabled);
    if (this.activeIndex >= this.enabledFiltered.length) {
      this.activeIndex = this.enabledFiltered.length - 1;
    }
    this.cdr.markForCheck();
  }
}
