// packages/react/src/components/Pagination/Pagination.tsx
import { clsx } from 'clsx';
import { ChevronLeft, ChevronRight } from 'lucide-react';

export interface PaginationProps {
  /** Page courante (1-indexed). */
  page: number;
  /** Nombre total de pages. */
  totalPages: number;
  /** Callback de changement de page. */
  onPageChange: (page: number) => void;
  /** Nombre de pages à afficher autour de la courante. Default: 1. */
  siblings?: number;
  /** Étiquette ARIA du `<nav>`. */
  'aria-label'?: string;
  className?: string;
}

/**
 * Calcule la liste de pages à afficher avec ellipses.
 * Ex: page=5, total=10, siblings=1 → [1, '...', 4, 5, 6, '...', 10]
 */
function buildPageList(
  page: number,
  totalPages: number,
  siblings: number,
): (number | 'ellipsis')[] {
  // Si peu de pages, on affiche tout sans ellipses
  const compact = 2 * siblings + 5; // first + last + current + 2*siblings + 2 ellipses au max
  if (totalPages <= compact) {
    return Array.from({ length: totalPages }, (_, i) => i + 1);
  }

  const pages: (number | 'ellipsis')[] = [];
  const left = Math.max(2, page - siblings);
  const right = Math.min(totalPages - 1, page + siblings);

  pages.push(1);
  if (left > 2) pages.push('ellipsis');
  for (let i = left; i <= right; i++) pages.push(i);
  if (right < totalPages - 1) pages.push('ellipsis');
  pages.push(totalPages);

  return pages;
}

/**
 * Pagination accessible : `<nav>` + `<ol>` + boutons.
 * Émet `onPageChange(page)` ; c'est l'app qui met à jour son état.
 */
export function Pagination({
  page,
  totalPages,
  onPageChange,
  siblings = 1,
  'aria-label': ariaLabel = 'Pagination',
  className,
}: PaginationProps) {
  if (totalPages <= 1) return null;

  const pages = buildPageList(page, totalPages, siblings);
  const canPrev = page > 1;
  const canNext = page < totalPages;

  return (
    <nav aria-label={ariaLabel}>
      <ol className={clsx('ori-pagination', className)}>
        <li className="ori-pagination__item">
          <button
            type="button"
            className="ori-pagination__link"
            onClick={() => canPrev && onPageChange(page - 1)}
            disabled={!canPrev}
            aria-label="Page précédente"
          >
            <ChevronLeft size={16} aria-hidden="true" />
          </button>
        </li>
        {pages.map((p, i) =>
          p === 'ellipsis' ? (
            <li key={`e-${i}`} className="ori-pagination__ellipsis" aria-hidden="true">
              …
            </li>
          ) : (
            <li key={p} className="ori-pagination__item">
              <button
                type="button"
                className="ori-pagination__link"
                aria-current={p === page ? 'page' : undefined}
                aria-label={`Page ${p}${p === page ? ', page courante' : ''}`}
                onClick={() => p !== page && onPageChange(p)}
              >
                {p}
              </button>
            </li>
          ),
        )}
        <li className="ori-pagination__item">
          <button
            type="button"
            className="ori-pagination__link"
            onClick={() => canNext && onPageChange(page + 1)}
            disabled={!canNext}
            aria-label="Page suivante"
          >
            <ChevronRight size={16} aria-hidden="true" />
          </button>
        </li>
      </ol>
    </nav>
  );
}

// packages/angular/src/components/pagination/pagination.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewEncapsulation,
} from '@angular/core';
import { LucideAngularModule, ChevronLeft, ChevronRight } from 'lucide-angular';

type LucideIconData = typeof ChevronLeft;

type PageItem = number | 'ellipsis';

function buildPageList(page: number, totalPages: number, siblings: number): PageItem[] {
  const compact = 2 * siblings + 5;
  if (totalPages <= compact) {
    return Array.from({ length: totalPages }, (_, i) => i + 1);
  }
  const pages: PageItem[] = [];
  const left = Math.max(2, page - siblings);
  const right = Math.min(totalPages - 1, page + siblings);
  pages.push(1);
  if (left > 2) pages.push('ellipsis');
  for (let i = left; i <= right; i++) pages.push(i);
  if (right < totalPages - 1) pages.push('ellipsis');
  pages.push(totalPages);
  return pages;
}

/**
 * Pagination accessible : `<nav>` + `<ol>` + boutons.
 * Émet `(pageChange)` ; c'est l'app qui met à jour son état.
 */
@Component({
  selector: 'ori-pagination',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    @if (totalPages > 1) {
      <nav [attr.aria-label]="ariaLabel">
        <ol class="ori-pagination">
          <li class="ori-pagination__item">
            <button
              type="button"
              class="ori-pagination__link"
              [disabled]="!canPrev"
              (click)="canPrev && pageChange.emit(page - 1)"
              aria-label="Page précédente"
            >
              <lucide-icon [img]="ChevronLeftIcon" [size]="16" aria-hidden="true"></lucide-icon>
            </button>
          </li>
          @for (item of pages; track $index) {
            @if (item === 'ellipsis') {
              <li class="ori-pagination__ellipsis" aria-hidden="true">…</li>
            } @else {
              <li class="ori-pagination__item">
                <button
                  type="button"
                  class="ori-pagination__link"
                  [attr.aria-current]="item === page ? 'page' : null"
                  [attr.aria-label]="
                    item === page ? 'Page ' + item + ', page courante' : 'Page ' + item
                  "
                  (click)="item !== page && pageChange.emit(item)"
                >
                  {{ item }}
                </button>
              </li>
            }
          }
          <li class="ori-pagination__item">
            <button
              type="button"
              class="ori-pagination__link"
              [disabled]="!canNext"
              (click)="canNext && pageChange.emit(page + 1)"
              aria-label="Page suivante"
            >
              <lucide-icon [img]="ChevronRightIcon" [size]="16" aria-hidden="true"></lucide-icon>
            </button>
          </li>
        </ol>
      </nav>
    }
  `,
})
export class OriPaginationComponent implements OnChanges {
  @Input() page: number = 1;
  @Input() totalPages: number = 1;
  @Input() siblings: number = 1;
  @Input() ariaLabel: string = 'Pagination';

  @Output() pageChange = new EventEmitter<number>();

  pages: PageItem[] = [];

  protected readonly ChevronLeftIcon: LucideIconData = ChevronLeft;
  protected readonly ChevronRightIcon: LucideIconData = ChevronRight;

  get canPrev(): boolean {
    return this.page > 1;
  }

  get canNext(): boolean {
    return this.page < this.totalPages;
  }

  ngOnChanges(_changes: SimpleChanges): void {
    this.pages = buildPageList(this.page, this.totalPages, this.siblings);
  }
}
