// packages/angular/src/components/select/select.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';

export type OriSelectSize = 'sm' | 'md' | 'lg';

export interface OriSelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

let nextUid = 0;

/**
 * Liste déroulante simple basée sur `<select>` natif.
 *
 * Choix volontaire (cf. décision E.1) : on garde le natif pour l'a11y,
 * la cohérence mobile (picker système) et le bundle minimal. Un
 * `<ori-combobox>` séparé sera introduit à la demande pour les cas
 * search / multi-select.
 *
 * Bind : compatible avec [(ngModel)] via [value] / (valueChange).
 */
@Component({
  selector: 'ori-select',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [class]="fieldClasses">
      @if (label) {
        <label [class]="labelClasses" [attr.for]="selectId">{{ label }}</label>
      }
      <select
        [id]="selectId"
        [class]="selectClasses"
        [value]="value ?? ''"
        [disabled]="disabled"
        [required]="required"
        [attr.name]="name || null"
        [attr.aria-invalid]="error ? 'true' : null"
        [attr.aria-describedby]="describedBy"
        (change)="onChange($event)"
        (blur)="blur.emit()"
      >
        @if (placeholder) {
          <option value="" disabled>{{ placeholder }}</option>
        }
        @for (opt of options; track opt.value) {
          <option [value]="opt.value" [disabled]="opt.disabled || null">{{ opt.label }}</option>
        }
      </select>
      @if (hint && !error) {
        <span [attr.id]="hintId" class="ori-field__hint">{{ hint }}</span>
      }
      @if (error) {
        <span [attr.id]="errorId" class="ori-field__error" role="alert">{{ error }}</span>
      }
    </div>
  `,
})
export class OriSelectComponent {
  @Input() label: string = '';
  @Input() hint: string = '';
  @Input() error: string = '';
  @Input() placeholder: string = '';
  @Input() size: OriSelectSize = 'md';
  @Input() value: string = '';
  @Input() options: OriSelectOption[] = [];
  @Input() required: boolean = false;
  @Input() disabled: boolean = false;
  @Input() id: string = '';
  @Input() name: string = '';
  @Input() wrapperClass: string = '';

  @Output() valueChange = new EventEmitter<string>();
  @Output() blur = new EventEmitter<void>();

  private readonly autoId = `pf-select-${++nextUid}`;

  get selectId(): string {
    return this.id || this.autoId;
  }

  get hintId(): string | null {
    return this.hint && !this.error ? `${this.selectId}-hint` : null;
  }

  get errorId(): string | null {
    return this.error ? `${this.selectId}-error` : null;
  }

  get describedBy(): string | null {
    const ids = [this.hintId, this.errorId].filter(Boolean) as string[];
    return ids.length ? ids.join(' ') : null;
  }

  get fieldClasses(): string {
    return ['ori-field', this.wrapperClass].filter((c): c is string => Boolean(c)).join(' ');
  }

  get labelClasses(): string {
    return ['ori-field__label', this.required ? 'ori-field__label--required' : null]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }

  get selectClasses(): string {
    return ['ori-select', this.size !== 'md' ? `ori-select--${this.size}` : null]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }

  onChange(event: Event): void {
    const v = (event.target as HTMLSelectElement).value;
    this.value = v;
    this.valueChange.emit(v);
  }
}

// packages/react/src/components/Select/Select.tsx
import { forwardRef, useId } from 'react';
import type { SelectHTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export type SelectSize = 'sm' | 'md' | 'lg';

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface SelectProps extends Omit<SelectHTMLAttributes<HTMLSelectElement>, 'size'> {
  label?: ReactNode;
  hint?: ReactNode;
  error?: ReactNode;
  required?: boolean;
  size?: SelectSize;
  /**
   * Liste d'options. Alternative à passer des `<option>` en children.
   * Si les deux sont fournis, `options` a la priorité.
   */
  options?: SelectOption[];
  /** Texte affiché tant qu'aucune option n'est sélectionnée. */
  placeholder?: string;
  wrapperClassName?: string;
}

/**
 * Select wrappant `<select>` natif.
 *
 * Choix volontaire (cf. décision E.1) : on garde le natif pour l'a11y,
 * la cohérence mobile (picker système) et le bundle minimal. Si un cas
 * d'usage demande search ou multi-select stylé, on introduira un
 * `<Combobox>` séparé sans casser cette API.
 */
export const Select = forwardRef<HTMLSelectElement, SelectProps>(function Select(
  {
    label,
    hint,
    error,
    required,
    size = 'md',
    options,
    placeholder,
    wrapperClassName,
    id,
    className,
    children,
    ...rest
  },
  ref,
) {
  const reactId = useId();
  const selectId = id ?? reactId;
  const hintId = hint ? `${selectId}-hint` : undefined;
  const errorId = error ? `${selectId}-error` : undefined;
  const describedBy = [hintId, errorId].filter(Boolean).join(' ') || undefined;

  return (
    <div className={clsx('ori-field', wrapperClassName)}>
      {label && (
        <label
          htmlFor={selectId}
          className={clsx('ori-field__label', required && 'ori-field__label--required')}
        >
          {label}
        </label>
      )}
      <select
        ref={ref}
        id={selectId}
        className={clsx('ori-select', size !== 'md' && `ori-select--${size}`, className)}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy}
        required={required}
        {...rest}
      >
        {placeholder && (
          <option value="" disabled>
            {placeholder}
          </option>
        )}
        {options
          ? options.map((opt) => (
              <option key={opt.value} value={opt.value} disabled={opt.disabled}>
                {opt.label}
              </option>
            ))
          : children}
      </select>
      {hint && !error && (
        <span id={hintId} className="ori-field__hint">
          {hint}
        </span>
      )}
      {error && (
        <span id={errorId} className="ori-field__error" role="alert">
          {error}
        </span>
      )}
    </div>
  );
});
