// packages/react/src/components/Switch/Switch.tsx
import { forwardRef, useId } from 'react';
import type { InputHTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export interface SwitchProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  label?: ReactNode;
  hint?: ReactNode;
  wrapperClassName?: string;
}

/**
 * Bascule on/off pour un réglage qui s'applique immédiatement (à la
 * différence d'un Checkbox qui s'applique après validation d'un formulaire).
 *
 * Sémantique HTML : c'est un `<input type="checkbox" role="switch">`. Ça
 * combine la gestion native (focus, ESC, formulaires) avec la sémantique
 * "switch" pour les lecteurs d'écran.
 */
export const Switch = forwardRef<HTMLInputElement, SwitchProps>(function Switch(
  { label, hint, wrapperClassName, id, className, disabled, ...rest },
  ref,
) {
  const reactId = useId();
  const inputId = id ?? reactId;
  const hintId = hint ? `${inputId}-hint` : undefined;

  return (
    <label
      className={clsx('ori-choice', wrapperClassName)}
      data-disabled={disabled ? 'true' : undefined}
      htmlFor={inputId}
    >
      <span className="ori-switch">
        <input
          ref={ref}
          id={inputId}
          type="checkbox"
          role="switch"
          className={clsx('ori-switch__input', className)}
          aria-describedby={hintId}
          disabled={disabled}
          {...rest}
        />
        <span className="ori-switch__track" aria-hidden="true" />
      </span>
      {(label || hint) && (
        <span className="ori-choice__label">
          {label}
          {hint && (
            <span id={hintId} className="ori-choice__hint">
              {hint}
            </span>
          )}
        </span>
      )}
    </label>
  );
});

// packages/angular/src/components/switch/switch.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';

let nextUid = 0;

/**
 * Bascule on/off pour un réglage qui s'applique immédiatement (à la
 * différence d'une checkbox qui s'applique après validation d'un formulaire).
 *
 * Sémantique HTML : `<input type="checkbox" role="switch">` - on hérite de
 * la gestion native (focus, formulaires) tout en exposant la sémantique
 * "switch" pour les lecteurs d'écran.
 */
@Component({
  selector: 'ori-switch',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <label
      [class]="wrapperClasses"
      [attr.data-disabled]="disabled ? 'true' : null"
      [attr.for]="inputId"
    >
      <span class="ori-switch">
        <input
          type="checkbox"
          role="switch"
          class="ori-switch__input"
          [id]="inputId"
          [checked]="checked"
          [disabled]="disabled"
          [attr.name]="name || null"
          [attr.aria-describedby]="hintId"
          (change)="onChange($event)"
        />
        <span class="ori-switch__track" aria-hidden="true"></span>
      </span>
      @if (label || hint) {
        <span class="ori-choice__label">
          {{ label }}
          @if (hint) {
            <span [attr.id]="hintId" class="ori-choice__hint">{{ hint }}</span>
          }
        </span>
      }
    </label>
  `,
})
export class OriSwitchComponent {
  @Input() label: string = '';
  @Input() hint: string = '';
  @Input() checked: boolean = false;
  @Input() disabled: boolean = false;
  @Input() id: string = '';
  @Input() name: string = '';
  @Input() wrapperClass: string = '';

  @Output() checkedChange = new EventEmitter<boolean>();

  private readonly autoId = `pf-switch-${++nextUid}`;

  get inputId(): string {
    return this.id || this.autoId;
  }

  get hintId(): string | null {
    return this.hint ? `${this.inputId}-hint` : null;
  }

  get wrapperClasses(): string {
    return ['ori-choice', this.wrapperClass].filter((c): c is string => Boolean(c)).join(' ');
  }

  onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.checkedChange.emit(target.checked);
  }
}
