// packages/react/src/marketing/FeatureGrid/FeatureGrid.tsx
import { forwardRef } from 'react';
import type { HTMLAttributes } from 'react';
import { clsx } from 'clsx';

export type FeatureGridProps = HTMLAttributes<HTMLDivElement>;

/**
 * Grille responsive de FeatureCard. Auto-fit sur des colonnes de 16rem
 * minimum, gap automatique. À combiner avec <FeatureCard>.
 */
export const FeatureGrid = forwardRef<HTMLDivElement, FeatureGridProps>(function FeatureGrid(
  { className, children, ...rest },
  ref,
) {
  return (
    <div ref={ref} className={clsx('ori-feature-grid', className)} {...rest}>
      {children}
    </div>
  );
});

// packages/angular/marketing/feature-grid/feature-grid.component.ts
import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';

/**
 * Grille responsive de FeatureCard. Auto-fit sur des colonnes de 16rem
 * minimum, gap automatique. À combiner avec `<ori-feature-card>`.
 */
@Component({
  selector: 'ori-feature-grid',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `<div class="ori-feature-grid"><ng-content></ng-content></div>`,
})
export class OriFeatureGridComponent {}
