// packages/react/src/components/Timeline/Timeline.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export type TimelineItemStatus = 'completed' | 'current' | 'pending';

export interface TimelineItem {
  id: string;
  /** Titre principal de l'événement. */
  title: ReactNode;
  /** Date / heure formatée (ex: '2026-04-23 14:30'). */
  timestamp: ReactNode;
  /** Acteur ou source (ex: 'Vous', 'Service A'). Optionnel. */
  actor?: ReactNode;
  /** Détail supplémentaire (ex: nom du fichier ajouté). Optionnel. */
  description?: ReactNode;
  /** Status visuel du dot. Default: 'completed' (le 1er item peut être 'current'). */
  status?: TimelineItemStatus;
  /**
   * Contenu custom du dot (par défaut : index numéroté). Permet d'injecter
   * une icône Lucide par exemple.
   */
  icon?: ReactNode;
}

export interface TimelineProps extends Omit<HTMLAttributes<HTMLOListElement>, 'children'> {
  items: TimelineItem[];
}

/**
 * Timeline verticale d'événements (historique de dossier, journal d'audit,
 * suivi d'actions). Pas d'animation, pas de pagination - l'app gère sa
 * donnée et la pagine si nécessaire.
 */
export function Timeline({ items, className, ...rest }: TimelineProps) {
  return (
    <ol className={clsx('ori-timeline', className)} {...rest}>
      {items.map((item, i) => {
        const status = item.status ?? 'completed';
        return (
          <li key={item.id} className={clsx('ori-timeline__item', `ori-timeline__item--${status}`)}>
            <span className="ori-timeline__dot" aria-hidden="true">
              {item.icon ?? i + 1}
            </span>
            <div className="ori-timeline__content">
              <span className="ori-timeline__title">{item.title}</span>
              <span className="ori-timeline__meta">
                {item.timestamp}
                {item.actor && <> · {item.actor}</>}
              </span>
              {item.description && (
                <span className="ori-timeline__description">{item.description}</span>
              )}
            </div>
          </li>
        );
      })}
    </ol>
  );
}

// packages/angular/src/components/timeline/timeline.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  TemplateRef,
  ViewEncapsulation,
} from '@angular/core';

export type OriTimelineItemStatus = 'completed' | 'current' | 'pending';

export interface OriTimelineItem {
  id: string;
  title: string;
  /** Date / heure formatée (ex: '2026-04-23 14:30'). */
  timestamp: string;
  /** Acteur ou source. Optionnel. */
  actor?: string;
  /** Détail supplémentaire. Optionnel. */
  description?: string;
  /** Status visuel du dot. Default: 'completed'. */
  status?: OriTimelineItemStatus;
}

/**
 * Timeline verticale d'événements (historique de dossier, journal d'audit,
 * suivi d'actions).
 *
 * Pour des icônes custom dans les dots, fournir `[iconTemplate]` qui reçoit
 * `{ $implicit: item, index }`. Sinon le dot affiche l'index numéroté.
 */
@Component({
  selector: 'ori-timeline',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <ol class="ori-timeline">
      @for (item of items; track item.id; let i = $index) {
        <li [class]="itemClassFor(item)">
          <span class="ori-timeline__dot" aria-hidden="true">
            @if (iconTemplate) {
              <ng-container
                [ngTemplateOutlet]="iconTemplate"
                [ngTemplateOutletContext]="{ $implicit: item, index: i }"
              ></ng-container>
            } @else {
              {{ i + 1 }}
            }
          </span>
          <div class="ori-timeline__content">
            <span class="ori-timeline__title">{{ item.title }}</span>
            <span class="ori-timeline__meta">
              {{ item.timestamp }}
              @if (item.actor) {
                · {{ item.actor }}
              }
            </span>
            @if (item.description) {
              <span class="ori-timeline__description">{{ item.description }}</span>
            }
          </div>
        </li>
      }
    </ol>
  `,
  imports: [CommonModule],
})
export class OriTimelineComponent {
  @Input() items: OriTimelineItem[] = [];
  @Input() iconTemplate?: TemplateRef<{ $implicit: OriTimelineItem; index: number }>;

  itemClassFor(item: OriTimelineItem): string {
    const status = item.status ?? 'completed';
    return `ori-timeline__item ori-timeline__item--${status}`;
  }
}
