// packages/angular/src/components/header/header.component.ts
import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';

/**
 * Header app-level en 3 zones (cf. décision J.1).
 *
 * Slots ng-content :
 * ```html
 * <ori-header>
 *   <ng-container brand><ori-logo title="..." /></ng-container>
 *   <ng-container nav><ori-main-navigation [items]="..." /></ng-container>
 *   <ng-container actions><ori-button>Se connecter</ori-button></ng-container>
 * </ori-header>
 * ```
 *
 * Aucune logique métier hardcodée. L'app insère ce qu'elle veut dans
 * la zone actions (auth, notifications, profil, etc., cf. J.5).
 */
@Component({
  selector: 'ori-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <header class="ori-header">
      <div class="ori-header__brand">
        <ng-content select="[brand]"></ng-content>
      </div>
      <div class="ori-header__nav">
        <ng-content select="[nav]"></ng-content>
      </div>
      <div class="ori-header__actions">
        <ng-content select="[actions]"></ng-content>
      </div>
    </header>
  `,
})
export class OriHeaderComponent {}

// packages/react/src/components/Header/Header.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';
import { Logo } from '../Logo/Logo.js';

export interface HeaderProps extends Omit<HTMLAttributes<HTMLElement>, 'title'> {
  /**
   * Logo personnalisé. Si omis, on rend le `<Logo>` par défaut avec
   * les props `title` et `subtitle`.
   */
  logo?: ReactNode;
  /** Titre passé au `<Logo>` par défaut. */
  title?: ReactNode;
  /** Sous-titre passé au `<Logo>` par défaut. */
  subtitle?: ReactNode;
  /** URL du logo (rendu comme `<a>`). */
  logoHref?: string;
}

/**
 * Header app-level en 3 zones (cf. décision J.1) :
 * - gauche : `<Header.Brand>` (par défaut, le `<Logo>` PF)
 * - centre : `<Header.Nav>` (typiquement un `<MainNavigation>`)
 * - droite : `<Header.Actions>` (zone applicative libre)
 *
 * Aucune logique métier hardcodée. L'app insère ce qu'elle veut dans
 * Actions (auth, notifications, profil, etc., cf. J.5).
 */
export function Header({
  logo,
  title,
  subtitle,
  logoHref,
  className,
  children,
  ...rest
}: HeaderProps) {
  // Si pas de children mais un logo/title/subtitle, on rend le brand
  // par défaut (cas d'usage minimal : `<Header />`)
  const hasChildren = Boolean(children);
  const defaultBrand = (
    <HeaderBrand>{logo ?? <Logo title={title} subtitle={subtitle} href={logoHref} />}</HeaderBrand>
  );

  return (
    <header className={clsx('ori-header', className)} {...rest}>
      {hasChildren ? children : defaultBrand}
    </header>
  );
}

export function HeaderBrand({ className, children, ...rest }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={clsx('ori-header__brand', className)} {...rest}>
      {children}
    </div>
  );
}

export function HeaderNav({ className, children, ...rest }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={clsx('ori-header__nav', className)} {...rest}>
      {children}
    </div>
  );
}

export function HeaderActions({ className, children, ...rest }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={clsx('ori-header__actions', className)} {...rest}>
      {children}
    </div>
  );
}

Header.Brand = HeaderBrand;
Header.Nav = HeaderNav;
Header.Actions = HeaderActions;
