// packages/react/src/components/Legal/LegalDefinitionList.tsx
import { forwardRef } from 'react';
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export interface LegalDefinitionListItem {
  term: ReactNode;
  description: ReactNode;
}

export interface LegalDefinitionListProps extends HTMLAttributes<HTMLDListElement> {
  items: LegalDefinitionListItem[];
}

/**
 * Liste de définitions clé/valeur pour les pages légales (adresse,
 * téléphone, courriel, numéro Tahiti, DPO, etc.).
 *
 * Rendue en grille responsive : libellé à gauche en gras, valeur à droite.
 */
export const LegalDefinitionList = forwardRef<HTMLDListElement, LegalDefinitionListProps>(
  function LegalDefinitionList({ items, className, ...rest }, ref) {
    return (
      <dl ref={ref} className={clsx('ori-legal-dl', className)} {...rest}>
        {items.map((item, i) => (
          <div key={i} style={{ display: 'contents' }}>
            <dt>{item.term}</dt>
            <dd>{item.description}</dd>
          </div>
        ))}
      </dl>
    );
  },
);

// packages/angular/src/components/legal-definition-list/legal-definition-list.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

export interface OriLegalDefinitionListItem {
  term: string;
  description: string;
}

/**
 * Liste de définitions clé/valeur pour les pages légales (adresse,
 * téléphone, courriel, numéro Tahiti, DPO, etc.).
 *
 * Rendue en grille responsive : libellé à gauche en gras, valeur à droite.
 */
@Component({
  selector: 'ori-legal-definition-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `<dl class="ori-legal-dl">
    @for (item of items; track item.term) {
      <dt>{{ item.term }}</dt>
      <dd>{{ item.description }}</dd>
    }
  </dl>`,
})
export class OriLegalDefinitionListComponent {
  @Input({ required: true }) items: OriLegalDefinitionListItem[] = [];
}
