// packages/react/src/components/Legal/LegalSection.tsx
import { forwardRef } from 'react';
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export type LegalSectionVariant = 'default' | 'flat';

export interface LegalSectionProps extends Omit<HTMLAttributes<HTMLElement>, 'title'> {
  /**
   * Titre de la section (h2 sémantique). Optionnel pour les blocs
   * périphériques (date de mise à jour, etc.).
   */
  title?: ReactNode;
  /**
   * `flat` : visuellement plus discret (fond muted, padding réduit),
   * pour des informations de bas de page comme la date de dernière
   * mise à jour.
   */
  variant?: LegalSectionVariant;
}

/**
 * Bloc thématique au sein d'un `<LegalLayout>`. Présente un titre h2 et
 * un corps de texte rythmé selon les conventions Ori (paragraphes, gras,
 * listes de définitions via `<LegalDefinitionList>`).
 */
export const LegalSection = forwardRef<HTMLElement, LegalSectionProps>(function LegalSection(
  { title, variant = 'default', className, children, ...rest },
  ref,
) {
  return (
    <section
      ref={ref}
      className={clsx(
        'ori-legal-section',
        variant !== 'default' && `ori-legal-section--${variant}`,
        className,
      )}
      {...rest}
    >
      {title && <h2 className="ori-legal-section__title">{title}</h2>}
      {children}
    </section>
  );
});

// packages/angular/src/components/legal-section/legal-section.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

export type OriLegalSectionVariant = 'default' | 'flat';

/**
 * Bloc thématique au sein d'un `<ori-legal-layout>`. Présente un titre
 * h2 et un corps de texte rythmé selon les conventions Ori.
 *
 * Variante `flat` : visuellement plus discret (fond muted, padding
 * réduit), pour un bloc de fin de page comme la date de mise à jour.
 */
@Component({
  selector: 'ori-legal-section',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `<section [class]="classes">
    @if (title) {
      <h2 class="ori-legal-section__title">{{ title }}</h2>
    }
    <ng-content></ng-content>
  </section>`,
})
export class OriLegalSectionComponent {
  @Input() title?: string;
  @Input() variant: OriLegalSectionVariant = 'default';

  get classes(): string {
    return [
      'ori-legal-section',
      this.variant !== 'default' ? `ori-legal-section--${this.variant}` : null,
    ]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }
}
