// packages/react/src/components/Footer/Footer.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export interface FooterColumn {
  title: ReactNode;
  links: { label: ReactNode; href: string }[];
}

export interface FooterProps extends HTMLAttributes<HTMLElement> {
  /** Texte de marque / signature institutionnelle. */
  brand?: ReactNode;
  /** Description courte sous la marque. */
  description?: ReactNode;
  /** Colonnes de liens (services, démarches, contact, etc.). */
  columns?: FooterColumn[];
  /** Mention légale en bas. */
  legal?: ReactNode;
  /** Liens utilitaires en bas (mentions légales, accessibilité, plan du site). */
  utilityLinks?: { label: ReactNode; href: string }[];
}

/**
 * Footer app-level. Construit en 3 zones empilées :
 * - en haut : brand/description + colonnes de liens
 * - séparateur
 * - en bas : mention légale + liens utilitaires (accessibilité, mentions, etc.)
 */
export function Footer({
  brand = 'Polynésie française',
  description,
  columns = [],
  legal,
  utilityLinks = [],
  className,
  children,
  ...rest
}: FooterProps) {
  return (
    <footer className={clsx('ori-footer', className)} {...rest}>
      {children ?? (
        <>
          <div className="ori-footer__content">
            <div className="ori-footer__brand">
              <strong style={{ color: 'var(--color-text-primary)', fontSize: '0.9375rem' }}>
                {brand}
              </strong>
              {description && <span>{description}</span>}
            </div>
            {columns.length > 0 && (
              <div className="ori-footer__columns">
                {columns.map((col, i) => (
                  <div key={i} className="ori-footer__column">
                    <span className="ori-footer__column-title">{col.title}</span>
                    {col.links.map((link, j) => (
                      <a key={j} href={link.href} className="ori-link ori-link--quiet">
                        {link.label}
                      </a>
                    ))}
                  </div>
                ))}
              </div>
            )}
          </div>
          {(legal || utilityLinks.length > 0) && (
            <div className="ori-footer__bottom">
              {legal && <span>{legal}</span>}
              {utilityLinks.length > 0 && (
                <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                  {utilityLinks.map((link, i) => (
                    <a key={i} href={link.href} className="ori-link ori-link--quiet">
                      {link.label}
                    </a>
                  ))}
                </div>
              )}
            </div>
          )}
        </>
      )}
    </footer>
  );
}

// packages/angular/src/components/footer/footer.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

export interface OriFooterColumn {
  title: string;
  links: { label: string; href: string }[];
}

export interface OriFooterUtilityLink {
  label: string;
  href: string;
}

/**
 * Footer app-level. Brand + colonnes de liens en haut, mention légale
 * + liens utilitaires (accessibilité, mentions, plan du site) en bas.
 */
@Component({
  selector: 'ori-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <footer class="ori-footer">
      <div class="ori-footer__content">
        <div class="ori-footer__brand">
          <strong style="color: var(--color-text-primary); font-size: 0.9375rem;">
            {{ brand }}
          </strong>
          @if (description) {
            <span>{{ description }}</span>
          }
        </div>
        @if (columns.length > 0) {
          <div class="ori-footer__columns">
            @for (col of columns; track col.title) {
              <div class="ori-footer__column">
                <span class="ori-footer__column-title">{{ col.title }}</span>
                @for (link of col.links; track link.href) {
                  <a [href]="link.href" class="ori-link ori-link--quiet">{{ link.label }}</a>
                }
              </div>
            }
          </div>
        }
      </div>
      @if (legal || utilityLinks.length > 0) {
        <div class="ori-footer__bottom">
          @if (legal) {
            <span>{{ legal }}</span>
          }
          @if (utilityLinks.length > 0) {
            <div style="display: flex; gap: 16px; flex-wrap: wrap;">
              @for (link of utilityLinks; track link.href) {
                <a [href]="link.href" class="ori-link ori-link--quiet">{{ link.label }}</a>
              }
            </div>
          }
        </div>
      }
    </footer>
  `,
})
export class OriFooterComponent {
  @Input() brand: string = 'Polynésie française';
  @Input() description: string = '';
  @Input() columns: OriFooterColumn[] = [];
  @Input() legal: string = '';
  @Input() utilityLinks: OriFooterUtilityLink[] = [];
}
