// packages/react/src/components/ErrorPage/ErrorPage.tsx
import { forwardRef } from 'react';
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export type ErrorPageVariant = 'default' | 'maintenance' | 'danger';

export interface ErrorPageProps extends Omit<HTMLAttributes<HTMLElement>, 'title'> {
  /**
   * Code court affiché en badge au-dessus du titre. Typiquement un code
   * HTTP ("404", "403", "500", "503") ou un mot-clé ("Maintenance").
   */
  code: ReactNode;
  /**
   * Titre explicite (h1) de la page d'erreur, en français usager.
   */
  title: ReactNode;
  /**
   * Description longue (1-3 phrases) qui explique ce qui s'est passé et
   * ce que l'usager peut faire.
   */
  description?: ReactNode;
  /**
   * CTAs : un bouton primaire (retour accueil) + éventuellement un secondaire
   * (réessayer, contacter le support). Projeté via children pour rester libre
   * sur le contenu (ori-button ou autre).
   */
  actions?: ReactNode;
  /**
   * Bloc de détail technique optionnel (référence d'incident, date de
   * fin de maintenance prévue, etc.).
   */
  detail?: ReactNode;
  /**
   * Variante visuelle. `maintenance` colore le badge en orange (warning),
   * `danger` en rouge (erreur serveur), `default` reste neutre.
   */
  variant?: ErrorPageVariant;
}

/**
 * Page d'erreur ou de maintenance pleine hauteur.
 *
 * Pattern composé : un seul composant suffit pour les cas usuels (404, 403,
 * 500, 503). Pour un cas particulier, projeter du contenu via `children`.
 */
export const ErrorPage = forwardRef<HTMLElement, ErrorPageProps>(function ErrorPage(
  { code, title, description, actions, detail, variant = 'default', className, children, ...rest },
  ref,
) {
  return (
    <main
      ref={ref}
      className={clsx(
        'ori-error-page',
        variant !== 'default' && `ori-error-page--${variant}`,
        className,
      )}
      role="main"
      {...rest}
    >
      <div className="ori-error-page__inner">
        <span className="ori-error-page__code">{code}</span>
        <h1 className="ori-error-page__title">{title}</h1>
        {description && <p className="ori-error-page__description">{description}</p>}
        {actions && <div className="ori-error-page__actions">{actions}</div>}
        {children}
        {detail && <div className="ori-error-page__detail">{detail}</div>}
      </div>
    </main>
  );
});

// packages/angular/src/components/error-page/error-page.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

export type OriErrorPageVariant = 'default' | 'maintenance' | 'danger';

/**
 * Page d'erreur ou de maintenance pleine hauteur.
 *
 * Pattern composé : un seul composant suffit pour les cas usuels (404, 403,
 * 500, 503). Le contenu (titre, description, CTAs) est passé en inputs ou
 * projeté via slots nommés (`[oriErrorActions]`, `[oriErrorDetail]`).
 *
 * Usage typique :
 *
 *   <ori-error-page
 *     code="404"
 *     title="Cette page est introuvable"
 *     description="...">
 *     <ori-button oriErrorActions variant="primary">Retour à l'accueil</ori-button>
 *   </ori-error-page>
 */
@Component({
  selector: 'ori-error-page',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `<main [class]="classes" role="main">
    <div class="ori-error-page__inner">
      <span class="ori-error-page__code">{{ code }}</span>
      <h1 class="ori-error-page__title">{{ title }}</h1>
      @if (description) {
        <p class="ori-error-page__description">{{ description }}</p>
      }
      <div class="ori-error-page__actions">
        <ng-content select="[oriErrorActions]"></ng-content>
      </div>
      <ng-content></ng-content>
      <div class="ori-error-page__detail">
        <ng-content select="[oriErrorDetail]"></ng-content>
      </div>
    </div>
  </main>`,
})
export class OriErrorPageComponent {
  @Input({ required: true }) code!: string;
  @Input({ required: true }) title!: string;
  @Input() description?: string;
  @Input() variant: OriErrorPageVariant = 'default';

  get classes(): string {
    return ['ori-error-page', this.variant !== 'default' ? `ori-error-page--${this.variant}` : null]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }
}
