// packages/angular/src/components/empty-state/empty-state.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

export type OriEmptyStateSize = 'sm' | 'md' | 'lg';

/**
 * EmptyState inline.
 *
 * Bloc d'absence de données : zone vide d'une liste, recherche sans résultat,
 * onboarding. Communique pourquoi c'est vide, ce que l'utilisateur peut
 * faire et comment.
 *
 * Pas de role ARIA dédié : c'est du contenu textuel normal qui vit dans le
 * flux. Pour une page entièrement vide (404), envisager `<ori-error-page>`
 * qui pose la sémantique de niveau page.
 *
 * Slots : `slot="icon"` (rendu en aria-hidden), `slot="actions"` (boutons,
 * 2 max recommandé).
 */
@Component({
  selector: 'ori-empty-state',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [class]="'ori-empty-state ori-empty-state--' + size">
      <span class="ori-empty-state__icon" aria-hidden="true">
        <ng-content select="[slot=icon]"></ng-content>
      </span>
      <h3 class="ori-empty-state__title">{{ title }}</h3>
      @if (description) {
        <p class="ori-empty-state__description">{{ description }}</p>
      }
      <div class="ori-empty-state__actions">
        <ng-content select="[slot=actions]"></ng-content>
      </div>
    </div>
  `,
})
export class OriEmptyStateComponent {
  @Input() title: string = '';
  @Input() description: string = '';
  @Input() size: OriEmptyStateSize = 'md';
}

// packages/react/src/components/EmptyState/EmptyState.tsx
import { forwardRef } from 'react';
import type { ReactNode } from 'react';
import { clsx } from 'clsx';

/**
 * EmptyState inline.
 *
 * Bloc d'absence de données, à utiliser quand une zone (liste, table,
 * recherche, page) ne contient rien à afficher. Communique trois choses :
 * pourquoi c'est vide, ce que l'utilisateur peut faire, comment le faire.
 *
 * Pas de role ARIA dédié : l'EmptyState est un contenu textuel normal qui
 * vit dans le flux du document. Si la page est entièrement composée d'un
 * EmptyState (404 par exemple), envisager `<ErrorPage>` à la place qui pose
 * la sémantique de niveau page.
 *
 * Tailles :
 * - `sm` : pour les petites zones (filtre vide dans une table, dropdown
 *   sans résultat) ; icône 32px, padding compact
 * - `md` : taille par défaut, pour la majorité des cas (liste vide d'une
 *   page applicative) ; icône 48px
 * - `lg` : pour les écrans entièrement vides (premier login, onboarding) ;
 *   icône 64px, padding aéré
 */

export type EmptyStateSize = 'sm' | 'md' | 'lg';

export interface EmptyStateProps {
  /** Icône décorative (rendue avec aria-hidden). */
  icon?: ReactNode;
  /** Titre court explicitant l'état vide. */
  title: ReactNode;
  /** Description optionnelle (1-2 phrases) sur le pourquoi et l'action. */
  description?: ReactNode;
  /** Boutons d'action ; 2 max (primaire + secondaire). */
  actions?: ReactNode;
  size?: EmptyStateSize;
  className?: string;
}

export const EmptyState = forwardRef<HTMLDivElement, EmptyStateProps>(function EmptyState(
  { icon, title, description, actions, size = 'md', className },
  ref,
) {
  return (
    <div ref={ref} className={clsx('ori-empty-state', `ori-empty-state--${size}`, className)}>
      {icon && (
        <span className="ori-empty-state__icon" aria-hidden="true">
          {icon}
        </span>
      )}
      <h3 className="ori-empty-state__title">{title}</h3>
      {description && <p className="ori-empty-state__description">{description}</p>}
      {actions && <div className="ori-empty-state__actions">{actions}</div>}
    </div>
  );
});
