// packages/angular/src/components/progress/progress.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

let nextUid = 0;

/**
 * Barre de progression basée sur l'élément `<progress>` natif
 * (cf. décision G.2). Mode indéterminé en omettant `value`.
 */
@Component({
  selector: 'ori-progress',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    @if (label) {
      <div class="ori-progress-wrap">
        <div class="ori-progress__label">
          <label [attr.for]="progressId">{{ label }}</label>
          @if (shouldShowValue) {
            <span class="ori-progress__value">{{ displayValue }}%</span>
          }
        </div>
        <progress
          [id]="progressId"
          class="ori-progress"
          [value]="value !== null ? value : null"
          [max]="max"
        ></progress>
      </div>
    } @else {
      <progress
        [id]="progressId"
        class="ori-progress"
        [value]="value !== null ? value : null"
        [max]="max"
      ></progress>
    }
  `,
})
export class OriProgressComponent {
  /** Valeur courante. `null` = mode indéterminé. */
  @Input() value: number | null = null;
  @Input() max: number = 100;
  @Input() label: string = '';
  /** Force l'affichage de la valeur en pourcentage (default : auto). */
  @Input() showValue: boolean | null = null;
  @Input() id: string = '';

  private readonly autoId = `pf-progress-${++nextUid}`;

  get progressId(): string {
    return this.id || this.autoId;
  }

  get displayValue(): number {
    if (this.value === null) return 0;
    return Math.round((this.value / this.max) * 100);
  }

  get shouldShowValue(): boolean {
    if (this.showValue !== null) return this.showValue;
    return Boolean(this.label) && this.value !== null;
  }
}

// packages/react/src/components/Progress/Progress.tsx
import { useId, type ProgressHTMLAttributes, type ReactNode } from 'react';
import { clsx } from 'clsx';

export interface ProgressProps extends Omit<ProgressHTMLAttributes<HTMLProgressElement>, 'max'> {
  /** Valeur courante 0..max. Omettre pour mode indéterminé. */
  value?: number;
  /** Maximum. Default: 100. */
  max?: number;
  /** Label affiché au-dessus de la barre. */
  label?: ReactNode;
  /**
   * Si `true`, affiche la valeur en pourcentage à droite du label.
   * Default : `true` quand `label` est fourni et `value` connu.
   */
  showValue?: boolean;
  className?: string;
}

/**
 * Barre de progression basée sur l'élément `<progress>` natif HTML
 * (cf. décision G.2). Mode indéterminé gratuit en omettant `value`.
 */
export function Progress({
  value,
  max = 100,
  label,
  showValue,
  className,
  id,
  ...rest
}: ProgressProps) {
  const reactId = useId();
  const progressId = id ?? reactId;
  const indeterminate = value === undefined;
  const displayValue = !indeterminate ? Math.round((value / max) * 100) : null;
  const shouldShowValue = showValue ?? (label && displayValue !== null);

  if (!label) {
    return (
      <progress
        id={progressId}
        value={value}
        max={max}
        className={clsx('ori-progress', className)}
        {...rest}
      />
    );
  }

  return (
    <div className="ori-progress-wrap">
      <div className="ori-progress__label">
        <label htmlFor={progressId}>{label}</label>
        {shouldShowValue && <span className="ori-progress__value">{displayValue}%</span>}
      </div>
      <progress
        id={progressId}
        value={value}
        max={max}
        className={clsx('ori-progress', className)}
        {...rest}
      />
    </div>
  );
}
