// packages/angular/src/components/date-picker/date-picker.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';

export type OriDatePickerSize = 'sm' | 'md' | 'lg';

let nextUid = 0;

/**
 * Sélecteur de date basé sur `<input type="date">` natif.
 *
 * Choix volontaire (cf. décision E.2) : on garde le natif. La valeur
 * est stockée au format ISO `yyyy-mm-dd`. L'affichage suit la locale
 * du navigateur (`JJ/MM/AAAA` en fr-FR/fr-PF). Pour un calendrier
 * custom (range, désactivation de jours), un composant dédié sera
 * introduit à la demande.
 *
 * Bind : compatible avec [(ngModel)] via [value] / (valueChange).
 */
@Component({
  selector: 'ori-date-picker',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [class]="fieldClasses">
      @if (label) {
        <label [class]="labelClasses" [attr.for]="inputId">{{ label }}</label>
      }
      <input
        type="date"
        [id]="inputId"
        [class]="inputClasses"
        [value]="value ?? ''"
        [disabled]="disabled"
        [required]="required"
        [attr.name]="name || null"
        [attr.min]="min || null"
        [attr.max]="max || null"
        [attr.aria-invalid]="error ? 'true' : null"
        [attr.aria-describedby]="describedBy"
        (input)="onInput($event)"
        (blur)="blur.emit()"
      />
      @if (hint && !error) {
        <span [attr.id]="hintId" class="ori-field__hint">{{ hint }}</span>
      }
      @if (error) {
        <span [attr.id]="errorId" class="ori-field__error" role="alert">{{ error }}</span>
      }
    </div>
  `,
})
export class OriDatePickerComponent {
  @Input() label: string = '';
  @Input() hint: string = '';
  @Input() error: string = '';
  @Input() size: OriDatePickerSize = 'md';
  /** Valeur ISO `yyyy-mm-dd`. */
  @Input() value: string = '';
  /** Date min ISO. */
  @Input() min: string = '';
  /** Date max ISO. */
  @Input() max: string = '';
  @Input() required: boolean = false;
  @Input() disabled: boolean = false;
  @Input() id: string = '';
  @Input() name: string = '';
  @Input() wrapperClass: string = '';

  @Output() valueChange = new EventEmitter<string>();
  @Output() blur = new EventEmitter<void>();

  private readonly autoId = `pf-date-${++nextUid}`;

  get inputId(): string {
    return this.id || this.autoId;
  }

  get hintId(): string | null {
    return this.hint && !this.error ? `${this.inputId}-hint` : null;
  }

  get errorId(): string | null {
    return this.error ? `${this.inputId}-error` : null;
  }

  get describedBy(): string | null {
    const ids = [this.hintId, this.errorId].filter(Boolean) as string[];
    return ids.length ? ids.join(' ') : null;
  }

  get fieldClasses(): string {
    return ['ori-field', this.wrapperClass].filter((c): c is string => Boolean(c)).join(' ');
  }

  get labelClasses(): string {
    return ['ori-field__label', this.required ? 'ori-field__label--required' : null]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }

  get inputClasses(): string {
    return ['ori-input', this.size !== 'md' ? `ori-input--${this.size}` : null]
      .filter((c): c is string => Boolean(c))
      .join(' ');
  }

  onInput(event: Event): void {
    const v = (event.target as HTMLInputElement).value;
    this.value = v;
    this.valueChange.emit(v);
  }
}

// packages/react/src/components/DatePicker/DatePicker.tsx
import { forwardRef, useId } from 'react';
import type { InputHTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export type DatePickerSize = 'sm' | 'md' | 'lg';

export interface DatePickerProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type' | 'size'
> {
  label?: ReactNode;
  hint?: ReactNode;
  error?: ReactNode;
  required?: boolean;
  size?: DatePickerSize;
  /**
   * Valeur au format ISO `yyyy-mm-dd` (format imposé par
   * `<input type="date">`). Le format d'affichage à l'écran dépend du
   * navigateur et de la locale système (en `fr-FR` ou `fr-PF`, c'est
   * `JJ/MM/AAAA` automatiquement).
   */
  value?: string;
  /** Date min ISO (yyyy-mm-dd). */
  min?: string;
  /** Date max ISO (yyyy-mm-dd). */
  max?: string;
  wrapperClassName?: string;
}

/**
 * DatePicker wrappant `<input type="date">`.
 *
 * Choix volontaire (cf. décision E.2) : on garde le natif. Le format
 * d'affichage suit la locale du navigateur ; la valeur reste ISO côté
 * modèle pour rester compatible avec les API. Pour des cas avancés
 * (range picker, désactivation de jours, locale custom), un composant
 * calendrier custom sera introduit plus tard à la demande.
 */
export const DatePicker = forwardRef<HTMLInputElement, DatePickerProps>(function DatePicker(
  { label, hint, error, required, size = 'md', wrapperClassName, id, className, ...rest },
  ref,
) {
  const reactId = useId();
  const inputId = id ?? reactId;
  const hintId = hint ? `${inputId}-hint` : undefined;
  const errorId = error ? `${inputId}-error` : undefined;
  const describedBy = [hintId, errorId].filter(Boolean).join(' ') || undefined;

  return (
    <div className={clsx('ori-field', wrapperClassName)}>
      {label && (
        <label
          htmlFor={inputId}
          className={clsx('ori-field__label', required && 'ori-field__label--required')}
        >
          {label}
        </label>
      )}
      <input
        ref={ref}
        id={inputId}
        type="date"
        className={clsx('ori-input', size !== 'md' && `ori-input--${size}`, className)}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy}
        required={required}
        {...rest}
      />
      {hint && !error && (
        <span id={hintId} className="ori-field__hint">
          {hint}
        </span>
      )}
      {error && (
        <span id={errorId} className="ori-field__error" role="alert">
          {error}
        </span>
      )}
    </div>
  );
});
