// packages/angular/src/components/checkbox/checkbox.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core';

let nextUid = 0;

/**
 * Case à cocher binaire avec état indéterminé optionnel.
 *
 * - Bind compatible avec [(ngModel)] via [checked] / (checkedChange).
 * - Indeterminate est une property DOM (pas un attribut), gérée via ViewChild.
 * - Auto-génère un id si non fourni pour câbler `<label for="...">`.
 */
@Component({
  selector: 'ori-checkbox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <label [class]="wrapperClasses" [attr.data-disabled]="disabled ? 'true' : null">
      <input
        #inputEl
        type="checkbox"
        class="ori-checkbox"
        [id]="inputId"
        [checked]="checked"
        [disabled]="disabled"
        [attr.name]="name || null"
        [attr.value]="value || null"
        [attr.aria-invalid]="error ? 'true' : null"
        [attr.aria-describedby]="describedBy"
        (change)="onChange($event)"
      />
      @if (label || hint || error) {
        <span class="ori-choice__label">
          {{ label }}
          @if (hint && !error) {
            <span [attr.id]="hintId" class="ori-choice__hint">{{ hint }}</span>
          }
          @if (error) {
            <span
              [attr.id]="errorId"
              class="ori-choice__hint"
              role="alert"
              style="color: var(--color-feedback-danger)"
              >{{ error }}</span
            >
          }
        </span>
      }
    </label>
  `,
})
export class OriCheckboxComponent implements AfterViewInit, OnChanges {
  @Input() label: string = '';
  @Input() hint: string = '';
  @Input() error: string = '';
  @Input() checked: boolean = false;
  @Input() indeterminate: boolean = false;
  @Input() disabled: boolean = false;
  @Input() id: string = '';
  @Input() name: string = '';
  @Input() value: string = '';
  @Input() wrapperClass: string = '';

  @Output() checkedChange = new EventEmitter<boolean>();

  @ViewChild('inputEl') private inputEl?: ElementRef<HTMLInputElement>;

  private readonly autoId = `pf-checkbox-${++nextUid}`;

  get inputId(): string {
    return this.id || this.autoId;
  }

  get hintId(): string | null {
    return this.hint && !this.error ? `${this.inputId}-hint` : null;
  }

  get errorId(): string | null {
    return this.error ? `${this.inputId}-error` : null;
  }

  get describedBy(): string | null {
    const ids = [this.hintId, this.errorId].filter(Boolean) as string[];
    return ids.length ? ids.join(' ') : null;
  }

  get wrapperClasses(): string {
    return ['ori-choice', this.wrapperClass].filter((c): c is string => Boolean(c)).join(' ');
  }

  ngAfterViewInit(): void {
    this.applyIndeterminate();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['indeterminate']) {
      this.applyIndeterminate();
    }
  }

  private applyIndeterminate(): void {
    if (this.inputEl) {
      this.inputEl.nativeElement.indeterminate = this.indeterminate;
    }
  }

  onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.checkedChange.emit(target.checked);
  }
}

// packages/react/src/components/Checkbox/Checkbox.tsx
import { forwardRef, useEffect, useId, useRef } from 'react';
import type { InputHTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export interface CheckboxProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type' | 'size'
> {
  label?: ReactNode;
  hint?: ReactNode;
  error?: ReactNode;
  /**
   * État indéterminé. Indépendant de `checked` (un checkbox indéterminé peut
   * être checked ou non, c'est une indication visuelle pour des sélections
   * partielles - typiquement le checkbox d'un header de table qui sélectionne
   * une partie des lignes).
   */
  indeterminate?: boolean;
  wrapperClassName?: string;
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  { label, hint, error, indeterminate, wrapperClassName, id, className, disabled, ...rest },
  ref,
) {
  const reactId = useId();
  const inputId = id ?? reactId;
  const hintId = hint ? `${inputId}-hint` : undefined;
  const errorId = error ? `${inputId}-error` : undefined;
  const describedBy = [hintId, errorId].filter(Boolean).join(' ') || undefined;

  // Indeterminate n'est pas un attribut HTML, c'est une property de l'élément
  // DOM uniquement. On la pose après le render via ref.
  const localRef = useRef<HTMLInputElement | null>(null);
  useEffect(() => {
    if (localRef.current) {
      localRef.current.indeterminate = Boolean(indeterminate);
    }
  }, [indeterminate]);

  return (
    <label
      className={clsx('ori-choice', wrapperClassName)}
      data-disabled={disabled ? 'true' : undefined}
    >
      <input
        ref={(node) => {
          localRef.current = node;
          if (typeof ref === 'function') ref(node);
          else if (ref) ref.current = node;
        }}
        id={inputId}
        type="checkbox"
        className={clsx('ori-checkbox', className)}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy}
        disabled={disabled}
        {...rest}
      />
      {(label || hint || error) && (
        <span className="ori-choice__label">
          {label}
          {hint && !error && (
            <span id={hintId} className="ori-choice__hint">
              {hint}
            </span>
          )}
          {error && (
            <span
              id={errorId}
              className="ori-choice__hint"
              role="alert"
              style={{ color: 'var(--color-feedback-danger)' }}
            >
              {error}
            </span>
          )}
        </span>
      )}
    </label>
  );
});
