// packages/angular/src/components/tabs/tabs.component.ts
import {
  AfterContentInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChildren,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  QueryList,
  ViewChildren,
  ViewEncapsulation,
  forwardRef,
  inject,
} from '@angular/core';

let nextUid = 0;

/**
 * Item d'un `<ori-tabs>`. Le contenu projeté correspond au panel.
 * Le panel n'est rendu que quand l'item est actif (parité React).
 */
@Component({
  selector: 'ori-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    @if (isActive) {
      <div
        role="tabpanel"
        [id]="tabsBaseId + '-panel-' + value"
        [attr.aria-labelledby]="tabsBaseId + '-tab-' + value"
        [attr.tabindex]="0"
        class="ori-tabs__panel"
      >
        <ng-content></ng-content>
      </div>
    }
  `,
})
export class OriTabComponent {
  @Input() value: string = '';
  @Input() label: string = '';
  @Input() disabled: boolean = false;

  /** Renseignés par le parent <ori-tabs>. */
  tabsBaseId: string = '';
  isActive: boolean = false;

  private readonly cdr = inject(ChangeDetectorRef);

  setActive(active: boolean): void {
    if (this.isActive !== active) {
      this.isActive = active;
      this.cdr.markForCheck();
    }
  }
}

/**
 * Onglets ARIA avec activation manuelle (cf. décision F.2).
 */
@Component({
  selector: 'ori-tabs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="ori-tabs">
      <div role="tablist" [attr.aria-label]="ariaLabel || null" class="ori-tabs__list">
        @for (tab of tabsArray; track tab.value) {
          <button
            #tabBtn
            type="button"
            role="tab"
            [id]="baseId + '-tab-' + tab.value"
            [attr.aria-selected]="tab.value === value"
            [attr.aria-controls]="baseId + '-panel-' + tab.value"
            [attr.tabindex]="tab.value === value ? 0 : -1"
            [disabled]="tab.disabled"
            class="ori-tabs__tab"
            (click)="select(tab.value)"
            (keydown)="onKeyDown($event, tab.value)"
          >
            {{ tab.label }}
          </button>
        }
      </div>
      <ng-content></ng-content>
    </div>
  `,
})
export class OriTabsComponent implements AfterContentInit {
  @Input() value: string = '';
  @Input() ariaLabel: string = '';
  @Output() valueChange = new EventEmitter<string>();

  @ContentChildren(forwardRef(() => OriTabComponent))
  private tabsRef?: QueryList<OriTabComponent>;

  @ViewChildren('tabBtn') private buttons?: QueryList<ElementRef<HTMLButtonElement>>;

  readonly baseId = `pf-tabs-${++nextUid}`;
  tabsArray: { value: string; label: string; disabled: boolean }[] = [];

  private readonly cdr = inject(ChangeDetectorRef);

  ngAfterContentInit(): void {
    this.refresh();
    this.tabsRef?.changes.subscribe(() => this.refresh());
  }

  private refresh(): void {
    if (!this.tabsRef) return;
    this.tabsArray = this.tabsRef.toArray().map((t) => ({
      value: t.value,
      label: t.label,
      disabled: t.disabled,
    }));
    this.tabsRef.forEach((t) => {
      t.tabsBaseId = this.baseId;
      t.setActive(t.value === this.value);
    });
    this.cdr.markForCheck();
  }

  select(value: string): void {
    if (this.value === value) return;
    this.value = value;
    this.valueChange.emit(value);
    this.tabsRef?.forEach((t) => t.setActive(t.value === value));
  }

  onKeyDown(event: KeyboardEvent, currentValue: string): void {
    const enabled = this.tabsArray.filter((t) => !t.disabled);
    if (!enabled.length) return;
    const currentIndex = enabled.findIndex((t) => t.value === currentValue);
    let nextIndex: number | null = null;
    switch (event.key) {
      case 'ArrowRight':
        nextIndex = (currentIndex + 1) % enabled.length;
        break;
      case 'ArrowLeft':
        nextIndex = (currentIndex - 1 + enabled.length) % enabled.length;
        break;
      case 'Home':
        nextIndex = 0;
        break;
      case 'End':
        nextIndex = enabled.length - 1;
        break;
    }
    if (nextIndex === null) return;
    event.preventDefault();
    const targetValue = enabled[nextIndex].value;
    const idx = this.tabsArray.findIndex((t) => t.value === targetValue);
    this.buttons?.toArray()[idx]?.nativeElement.focus();
  }
}

// packages/react/src/components/Tabs/Tabs.tsx
import {
  createContext,
  useCallback,
  useContext,
  useId,
  useRef,
  useState,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import { clsx } from 'clsx';

interface TabsContextValue {
  baseId: string;
  selectedValue: string;
  setSelectedValue: (value: string) => void;
  registerTab: (value: string, ref: HTMLButtonElement | null) => void;
  focusAdjacent: (currentValue: string, direction: 1 | -1 | 'first' | 'last') => void;
}

const TabsContext = createContext<TabsContextValue | null>(null);

function useTabsContext(): TabsContextValue {
  const ctx = useContext(TabsContext);
  if (!ctx) throw new Error('Tabs.* must be used inside <Tabs>');
  return ctx;
}

export interface TabsProps {
  /** Valeur du tab actif (mode contrôlé). */
  value?: string;
  /** Valeur initiale (mode incontrôlé). */
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  className?: string;
  children?: ReactNode;
}

/**
 * Tabs ARIA avec activation manuelle (cf. décision F.2).
 *
 * Usage :
 * ```tsx
 * <Tabs defaultValue="profile">
 *   <Tabs.List aria-label="Réglages">
 *     <Tabs.Tab value="profile">Profil</Tabs.Tab>
 *     <Tabs.Tab value="notifications">Notifications</Tabs.Tab>
 *   </Tabs.List>
 *   <Tabs.Panel value="profile">…</Tabs.Panel>
 *   <Tabs.Panel value="notifications">…</Tabs.Panel>
 * </Tabs>
 * ```
 */
export function Tabs({ value, defaultValue, onValueChange, className, children }: TabsProps) {
  const baseId = useId();
  const [internalValue, setInternalValue] = useState(defaultValue ?? '');
  const isControlled = value !== undefined;
  const selectedValue = isControlled ? value : internalValue;

  const tabsRef = useRef<Map<string, HTMLButtonElement | null>>(new Map());

  const setSelectedValue = useCallback(
    (next: string) => {
      if (!isControlled) setInternalValue(next);
      onValueChange?.(next);
    },
    [isControlled, onValueChange],
  );

  const registerTab = useCallback((value: string, ref: HTMLButtonElement | null) => {
    if (ref) tabsRef.current.set(value, ref);
    else tabsRef.current.delete(value);
  }, []);

  const focusAdjacent = useCallback(
    (currentValue: string, direction: 1 | -1 | 'first' | 'last') => {
      const enabled = Array.from(tabsRef.current.entries()).filter(([, el]) => el && !el.disabled);
      if (!enabled.length) return;
      let nextIndex: number;
      if (direction === 'first') {
        nextIndex = 0;
      } else if (direction === 'last') {
        nextIndex = enabled.length - 1;
      } else {
        const currentIndex = enabled.findIndex(([v]) => v === currentValue);
        nextIndex = (currentIndex + direction + enabled.length) % enabled.length;
      }
      const entry = enabled[nextIndex];
      if (entry) entry[1]?.focus();
    },
    [],
  );

  return (
    <TabsContext.Provider
      value={{ baseId, selectedValue, setSelectedValue, registerTab, focusAdjacent }}
    >
      <div className={clsx('ori-tabs', className)}>{children}</div>
    </TabsContext.Provider>
  );
}

export interface TabsListProps {
  'aria-label'?: string;
  className?: string;
  children?: ReactNode;
}

function TabsList({ 'aria-label': ariaLabel, className, children }: TabsListProps) {
  return (
    <div role="tablist" aria-label={ariaLabel} className={clsx('ori-tabs__list', className)}>
      {children}
    </div>
  );
}

export interface TabsTabProps {
  value: string;
  disabled?: boolean;
  className?: string;
  children?: ReactNode;
}

function TabsTab({ value, disabled, className, children }: TabsTabProps) {
  const { baseId, selectedValue, setSelectedValue, registerTab, focusAdjacent } = useTabsContext();
  const isSelected = selectedValue === value;

  const handleKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
    switch (e.key) {
      case 'ArrowRight':
        e.preventDefault();
        focusAdjacent(value, 1);
        break;
      case 'ArrowLeft':
        e.preventDefault();
        focusAdjacent(value, -1);
        break;
      case 'Home':
        e.preventDefault();
        focusAdjacent(value, 'first');
        break;
      case 'End':
        e.preventDefault();
        focusAdjacent(value, 'last');
        break;
    }
  };

  return (
    <button
      type="button"
      role="tab"
      id={`${baseId}-tab-${value}`}
      aria-selected={isSelected}
      aria-controls={`${baseId}-panel-${value}`}
      tabIndex={isSelected ? 0 : -1}
      disabled={disabled}
      ref={(el) => registerTab(value, el)}
      className={clsx('ori-tabs__tab', className)}
      onClick={() => setSelectedValue(value)}
      onKeyDown={handleKeyDown}
    >
      {children}
    </button>
  );
}

export interface TabsPanelProps {
  value: string;
  className?: string;
  children?: ReactNode;
}

function TabsPanel({ value, className, children }: TabsPanelProps) {
  const { baseId, selectedValue } = useTabsContext();
  const isActive = selectedValue === value;
  return (
    <div
      role="tabpanel"
      id={`${baseId}-panel-${value}`}
      aria-labelledby={`${baseId}-tab-${value}`}
      hidden={!isActive}
      tabIndex={0}
      className={clsx('ori-tabs__panel', className)}
    >
      {isActive && children}
    </div>
  );
}

Tabs.List = TabsList;
Tabs.Tab = TabsTab;
Tabs.Panel = TabsPanel;
