// packages/angular/src/components/steps/steps.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import { LucideAngularModule, Check } from 'lucide-angular';

type LucideIconData = typeof Check;

export type OriStepStatus = 'completed' | 'current' | 'todo';

export interface OriStepItem {
  title: string;
  description?: string;
}

/**
 * Indicateur de progression d'un workflow (cf. décision F.3).
 * Read-only par défaut, opt-in `[clickable]="true"` pour permettre
 * le retour à une étape précédente complétée.
 */
@Component({
  selector: 'ori-steps',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <ol class="ori-steps">
      @for (step of steps; track $index; let i = $index; let last = $last) {
        @let status = getStatus(i);
        @let isClickable = clickable && status === 'completed';
        <li
          [class]="'ori-steps__item ori-steps__item--' + status"
          [attr.aria-current]="status === 'current' ? 'step' : null"
        >
          @if (isClickable) {
            <button
              type="button"
              class="ori-steps__button"
              [attr.aria-label]="'Revenir à l\\'étape ' + (i + 1)"
              (click)="stepClick.emit(i)"
            >
              <span class="ori-steps__marker" aria-hidden="true">
                @if (status === 'completed') {
                  <lucide-icon [img]="CheckIcon" [size]="16"></lucide-icon>
                } @else {
                  {{ i + 1 }}
                }
              </span>
              <span class="ori-steps__label">
                <span class="ori-steps__title">{{ step.title }}</span>
                @if (step.description) {
                  <span class="ori-steps__description">{{ step.description }}</span>
                }
              </span>
            </button>
          } @else {
            <span class="ori-steps__marker" aria-hidden="true">
              @if (status === 'completed') {
                <lucide-icon [img]="CheckIcon" [size]="16"></lucide-icon>
              } @else {
                {{ i + 1 }}
              }
            </span>
            <span class="ori-steps__label">
              <span class="ori-steps__title">{{ step.title }}</span>
              @if (step.description) {
                <span class="ori-steps__description">{{ step.description }}</span>
              }
            </span>
          }
        </li>
        @if (!last) {
          <li class="ori-steps__separator" aria-hidden="true"></li>
        }
      }
    </ol>
  `,
})
export class OriStepsComponent {
  @Input() steps: OriStepItem[] = [];
  @Input() current: number = 0;
  @Input() clickable: boolean = false;

  @Output() stepClick = new EventEmitter<number>();

  protected readonly CheckIcon: LucideIconData = Check;

  getStatus(index: number): OriStepStatus {
    if (index < this.current) return 'completed';
    if (index === this.current) return 'current';
    return 'todo';
  }
}

// packages/react/src/components/Steps/Steps.tsx
import { Fragment, type ReactNode } from 'react';
import { clsx } from 'clsx';
import { Check } from 'lucide-react';

export type StepStatus = 'completed' | 'current' | 'todo';

export interface StepItem {
  /** Titre court de l'étape (ex: "Identité"). */
  title: ReactNode;
  /** Description optionnelle (ex: "Vos informations personnelles"). */
  description?: ReactNode;
}

export interface StepsProps {
  steps: StepItem[];
  /** Index 0-based de l'étape courante. */
  current: number;
  /**
   * Si `true`, les étapes complétées (avant `current`) sont cliquables.
   * Cf. décision F.3 : read-only par défaut. Default: false.
   */
  clickable?: boolean;
  /** Callback de clic sur une étape (uniquement si `clickable`). */
  onStepClick?: (index: number) => void;
  className?: string;
}

/**
 * Steps : indicateur de progression d'un workflow multi-étapes.
 * Read-only par défaut, opt-in `clickable` pour permettre le retour
 * à une étape précédente complétée (cf. décision F.3).
 */
export function Steps({ steps, current, clickable, onStepClick, className }: StepsProps) {
  const getStatus = (index: number): StepStatus =>
    index < current ? 'completed' : index === current ? 'current' : 'todo';

  return (
    <ol className={clsx('ori-steps', className)}>
      {steps.map((step, index) => {
        const status = getStatus(index);
        const isClickable = clickable && status === 'completed';
        const itemClass = clsx('ori-steps__item', `ori-steps__item--${status}`);

        const marker = (
          <span className="ori-steps__marker" aria-hidden="true">
            {status === 'completed' ? <Check size={16} /> : index + 1}
          </span>
        );

        const label = (
          <span className="ori-steps__label">
            <span className="ori-steps__title">{step.title}</span>
            {step.description && <span className="ori-steps__description">{step.description}</span>}
          </span>
        );

        return (
          <Fragment key={index}>
            <li className={itemClass} aria-current={status === 'current' ? 'step' : undefined}>
              {isClickable ? (
                <button
                  type="button"
                  className="ori-steps__button"
                  onClick={() => onStepClick?.(index)}
                  aria-label={`Revenir à l'étape ${index + 1}`}
                >
                  {marker}
                  {label}
                </button>
              ) : (
                <>
                  {marker}
                  {label}
                </>
              )}
            </li>
            {index < steps.length - 1 && <li className="ori-steps__separator" aria-hidden="true" />}
          </Fragment>
        );
      })}
    </ol>
  );
}
