// packages/angular/src/components/highlight/highlight.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  ViewEncapsulation,
} from '@angular/core';

interface HighlightSegment {
  text: string;
  highlighted: boolean;
}

/**
 * Surlignage basé sur l'élément `<mark>` natif HTML5.
 *
 * Trois modes :
 * - Direct : `<ori-highlight text="texte"></ori-highlight>` surligne tout
 *   (pas de prop `query` du tout, donc undefined)
 * - Recherche inactive : `<ori-highlight text="..." [query]="''">`
 *   rend le texte tel quel (recherche en cours mais champ vide)
 * - Recherche active : `<ori-highlight text="..." query="ti">` surligne
 *   uniquement les occurrences (insensible à la casse)
 *
 * Le découpage en segments est fait côté composant : on rend des
 * `<span>` et `<mark>` Angular-safe, pas de bypass de sanitizer.
 */
@Component({
  selector: 'ori-highlight',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    @if (query === undefined) {
      <mark class="ori-highlight">{{ text }}</mark>
    } @else if (query === '') {
      {{ text }}
    } @else {
      @for (seg of segments; track $index) {
        @if (seg.highlighted) {
          <mark class="ori-highlight">{{ seg.text }}</mark>
        } @else {
          {{ seg.text }}
        }
      }
    }
  `,
})
export class OriHighlightComponent implements OnChanges {
  @Input() text: string = '';
  @Input() query?: string;

  segments: HighlightSegment[] = [];

  ngOnChanges(_changes: SimpleChanges): void {
    this.segments = this.computeSegments();
  }

  private computeSegments(): HighlightSegment[] {
    if (!this.query || !this.text) return [];
    const result: HighlightSegment[] = [];
    const lowerText = this.text.toLowerCase();
    const lowerQuery = this.query.toLowerCase();
    let cursor = 0;
    while (cursor < this.text.length) {
      const idx = lowerText.indexOf(lowerQuery, cursor);
      if (idx === -1) {
        result.push({ text: this.text.slice(cursor), highlighted: false });
        break;
      }
      if (idx > cursor) {
        result.push({ text: this.text.slice(cursor, idx), highlighted: false });
      }
      result.push({
        text: this.text.slice(idx, idx + this.query.length),
        highlighted: true,
      });
      cursor = idx + this.query.length;
    }
    return result;
  }
}

// packages/react/src/components/Highlight/Highlight.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { clsx } from 'clsx';

export interface HighlightProps extends HTMLAttributes<HTMLElement> {
  /**
   * Si fourni, surligne automatiquement les occurrences de cette
   * sous-chaîne dans `children` (insensible à la casse, sans regex).
   * Utile pour des résultats de recherche.
   */
  query?: string;
  children?: ReactNode;
}

/**
 * Surlignage sémantique basé sur l'élément `<mark>` natif HTML5
 * (annoncé correctement par les lecteurs d'écran).
 *
 * Mode 1 : `<Highlight>texte</Highlight>` - surligne tout le contenu
 * Mode 2 : `<Highlight query="ti">titre</Highlight>` - surligne
 *           uniquement les occurrences de `query`
 *
 * Quand `query` est passé mais vide (recherche inactive), le composant
 * renvoie les `children` tels quels sans surlignage. C'est le cas type
 * d'une liste filtrée par un input dont la valeur courante est `""`.
 */
export function Highlight({ query, className, children, ...rest }: HighlightProps) {
  // Mode 1 : pas de prop `query` du tout - surligne tout
  if (query === undefined) {
    return (
      <mark className={clsx('ori-highlight', className)} {...rest}>
        {children}
      </mark>
    );
  }

  // Mode 2 (recherche) : query passé mais vide ou children non-string -
  // pas de match possible, on rend sans surlignage
  if (query === '' || typeof children !== 'string') {
    return <>{children}</>;
  }

  // Mode "auto-highlight" sur une chaîne
  const text = children;
  const lowerText = text.toLowerCase();
  const lowerQuery = query.toLowerCase();
  const parts: ReactNode[] = [];
  let cursor = 0;
  let i = 0;
  while (cursor < text.length) {
    const idx = lowerText.indexOf(lowerQuery, cursor);
    if (idx === -1) {
      parts.push(text.slice(cursor));
      break;
    }
    if (idx > cursor) parts.push(text.slice(cursor, idx));
    parts.push(
      <mark key={i++} className={clsx('ori-highlight', className)} {...rest}>
        {text.slice(idx, idx + query.length)}
      </mark>,
    );
    cursor = idx + query.length;
  }
  return <>{parts}</>;
}
