// packages/angular/src/components/app-shell/app-shell.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import { LucideAngularModule, ChevronLeft, ChevronRight } from 'lucide-angular';

type LucideIconData = typeof ChevronLeft;

const MAIN_ID = 'ori-app-shell-main';

/**
 * AppShell : layout d'application.
 *
 * Pose le squelette d'une app interne ou usager : header sticky en haut,
 * sidebar à gauche (optionnelle, drawer responsive sur mobile), main au
 * centre, footer en bas (optionnel). Inclut un skip link "Aller au contenu
 * principal" pour l'a11y clavier.
 *
 * Volontairement agnostique : ne fournit pas de Header / Sidebar / Footer
 * tout faits, l'app projette ce qu'elle veut via les slots :
 * - `slot="header"`
 * - `slot="sidebar"` (la présence du contenu active le mode "with-sidebar")
 * - `slot="footer"`
 * - contenu principal = projection par défaut
 *
 * Sidebar drawer mobile : à viewport < 768px, la sidebar est cachée et
 * accessible via un toggle externe (le bouton vit dans le header projeté).
 * L'app contrôle l'état via `[sidebarOpen]` + `(sidebarOpenChange)`.
 * ESC ferme le drawer.
 *
 * a11y :
 * - skip link en première position, visible au focus uniquement
 * - main avec id="ori-app-shell-main" + tabindex=-1 pour le skip link
 * - drawer mobile : aria-modal + scrim cliquable
 */
@Component({
  selector: 'ori-app-shell',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      [class]="
        'ori-app-shell ' +
        (hasSidebar ? 'ori-app-shell--with-sidebar ' : '') +
        (sidebarOpen ? 'ori-app-shell--sidebar-open' : '')
      "
    >
      <a [attr.href]="'#' + mainId" class="ori-app-shell__skip-link">{{ skipLinkLabel }}</a>
      <div #headerSlot class="ori-app-shell__header" [hidden]="!hasHeader">
        <ng-content select="[slot=header]"></ng-content>
      </div>
      <div class="ori-app-shell__body">
        @if (hasSidebar) {
          <aside class="ori-app-shell__sidebar" aria-label="Navigation latérale">
            <ng-content select="[slot=sidebar]"></ng-content>
          </aside>
          <button
            type="button"
            class="ori-app-shell__sidebar-toggle"
            [attr.aria-label]="sidebarOpen ? collapseSidebarLabel : expandSidebarLabel"
            [attr.aria-expanded]="sidebarOpen"
            [attr.aria-controls]="mainId"
            (click)="toggleSidebar()"
          >
            <lucide-icon
              [img]="sidebarOpen ? ChevronLeftIcon : ChevronRightIcon"
              [size]="16"
              aria-hidden="true"
            ></lucide-icon>
          </button>
          <div
            class="ori-app-shell__scrim"
            role="button"
            tabindex="-1"
            [attr.aria-label]="closeSidebarLabel"
            (click)="closeSidebar()"
          ></div>
        }
        <main [id]="mainId" tabindex="-1" class="ori-app-shell__main">
          <ng-content></ng-content>
        </main>
      </div>
      <div #footerSlot class="ori-app-shell__footer" [hidden]="!hasFooter">
        <ng-content select="[slot=footer]"></ng-content>
      </div>
    </div>
  `,
})
export class OriAppShellComponent {
  @Input() skipLinkLabel: string = 'Aller au contenu principal';
  @Input() closeSidebarLabel: string = 'Fermer le menu';
  @Input() collapseSidebarLabel: string = 'Masquer la navigation latérale';
  @Input() expandSidebarLabel: string = 'Afficher la navigation latérale';

  protected readonly ChevronLeftIcon: LucideIconData = ChevronLeft;
  protected readonly ChevronRightIcon: LucideIconData = ChevronRight;
  /**
   * État de la sidebar. Pilote l'affichage sur tous les viewports :
   * - desktop ≥ 768px : `true` = visible in-flow, `false` = masquée
   * - mobile < 768px : `true` = drawer ouvert, `false` = drawer fermé
   *
   * Default : `true` (sidebar visible par défaut sur desktop).
   */
  @Input() sidebarOpen: boolean = true;

  @Output() sidebarOpenChange = new EventEmitter<boolean>();

  protected readonly mainId = MAIN_ID;

  // Détection de la présence des slots projetés via ContentChild
  // d'attribut. Quand le slot existe dans le template parent, ces refs
  // sont définies ; sinon undefined.
  @ContentChild('headerSlotRef') protected headerSlotProvided?: unknown;
  @ContentChild('sidebarSlotRef') protected sidebarSlotProvided?: unknown;
  @ContentChild('footerSlotRef') protected footerSlotProvided?: unknown;

  // Note pragmatique : ContentChild sur un attribut projeté ne fonctionne pas
  // de la même manière qu'en React. On expose donc des @Input pour piloter
  // explicitement la présence des zones depuis l'app, plutôt que de tenter
  // une détection automatique fragile. C'est le pattern standard côté Angular.
  /** Indique si le slot header est présent. Default: true (le slot vide reste discret). */
  @Input() hasHeader: boolean = true;
  /** Indique si la sidebar est présente. Default: false (layout simple par défaut). */
  @Input() hasSidebar: boolean = false;
  /** Indique si le slot footer est présent. Default: false. */
  @Input() hasFooter: boolean = false;

  closeSidebar(): void {
    if (!this.sidebarOpen) return;
    this.sidebarOpen = false;
    this.sidebarOpenChange.emit(false);
  }

  toggleSidebar(): void {
    this.sidebarOpen = !this.sidebarOpen;
    this.sidebarOpenChange.emit(this.sidebarOpen);
  }

  @HostListener('document:keydown.escape')
  protected onEscape(): void {
    if (this.sidebarOpen) this.closeSidebar();
  }
}

// packages/react/src/components/AppShell/AppShell.tsx
import { forwardRef, useCallback, useEffect } from 'react';
import type { ReactNode } from 'react';
import { clsx } from 'clsx';
import { ChevronLeft, ChevronRight } from 'lucide-react';

/**
 * AppShell : layout d'application.
 *
 * Pose le squelette d'une app interne ou usager : header sticky en haut,
 * sidebar à gauche (optionnelle, drawer responsive sur mobile), main au
 * centre, footer en bas (optionnel). Inclut un skip link "Aller au contenu
 * principal" pour l'a11y clavier.
 *
 * Volontairement agnostique : ne fournit pas de Header / Sidebar / Footer
 * tout faits, l'app projette ce qu'elle veut. Pour l'usage standard, brancher
 * les composants Ori `<Header>`, `<SideMenu>` et `<Footer>`.
 *
 * Sidebar pilotable sur tous les viewports via `sidebarOpen` /
 * `onSidebarOpenChange` :
 *
 * - Desktop ≥ 768px : `sidebarOpen=true` (défaut) la sidebar est visible
 *   in-flow à gauche. `sidebarOpen=false` la sidebar est masquée et le main
 *   prend toute la largeur.
 * - Mobile < 768px : la sidebar est en drawer hors-flux. `sidebarOpen=true`
 *   l'ouvre par-dessus le scrim, `sidebarOpen=false` la ferme.
 *
 * Sur desktop, le composant rend lui-même un bouton de toggle intégré
 * (chevron) sur le bord droit de la sidebar quand elle est visible, qui
 * glisse à gauche du main quand elle est masquée. Le bouton est rendu
 * uniquement si `onSidebarOpenChange` est fourni (sans callback, le
 * toggle ne servirait à rien). Sur mobile, le bouton est masqué : le
 * drawer ferme via le scrim cliquable et la touche Escape.
 *
 * a11y :
 * - skip link en première position, visible au focus uniquement
 * - main a `id="ori-app-shell-main"` + `tabindex={-1}` pour le skip link
 * - drawer mobile : `aria-modal="true"` + scrim cliquable
 */

export interface AppShellProps {
  /** Contenu projeté en haut, sticky (généralement <Header>). */
  header?: ReactNode;
  /** Contenu projeté à gauche (généralement <SideMenu>). Optionnel : si absent, pas de sidebar. */
  sidebar?: ReactNode;
  /** Contenu projeté en bas, hors flux scroll (généralement <Footer>). Optionnel. */
  footer?: ReactNode;
  /** Contenu principal. Rendu dans `<main>` avec id pour le skip link. */
  children?: ReactNode;
  /** Texte du skip link. */
  skipLinkLabel?: string;
  /**
   * État de la sidebar. Pilote l'affichage sur tous les viewports :
   * - desktop ≥ 768px : `true` = visible in-flow, `false` = masquée
   * - mobile < 768px : `true` = drawer ouvert (sur scrim), `false` = drawer fermé
   *
   * Default : `true` (sidebar visible par défaut sur desktop).
   */
  sidebarOpen?: boolean;
  onSidebarOpenChange?: (open: boolean) => void;
  /** Label accessible du scrim (lecteur d'écran). */
  closeSidebarLabel?: string;
  /** Label accessible du bouton de toggle quand la sidebar est ouverte. */
  collapseSidebarLabel?: string;
  /** Label accessible du bouton de toggle quand la sidebar est fermée. */
  expandSidebarLabel?: string;
  className?: string;
}

const MAIN_ID = 'ori-app-shell-main';

export const AppShell = forwardRef<HTMLDivElement, AppShellProps>(function AppShell(
  {
    header,
    sidebar,
    footer,
    children,
    skipLinkLabel = 'Aller au contenu principal',
    sidebarOpen = true,
    onSidebarOpenChange,
    closeSidebarLabel = 'Fermer le menu',
    collapseSidebarLabel = 'Masquer la navigation latérale',
    expandSidebarLabel = 'Afficher la navigation latérale',
    className,
  },
  ref,
) {
  const closeSidebar = useCallback(() => {
    onSidebarOpenChange?.(false);
  }, [onSidebarOpenChange]);

  // Fermer le drawer sur ESC quand il est ouvert.
  useEffect(() => {
    if (!sidebarOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeSidebar();
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [sidebarOpen, closeSidebar]);

  return (
    <div
      ref={ref}
      className={clsx(
        'ori-app-shell',
        sidebar && 'ori-app-shell--with-sidebar',
        sidebarOpen && 'ori-app-shell--sidebar-open',
        className,
      )}
    >
      <a href={`#${MAIN_ID}`} className="ori-app-shell__skip-link">
        {skipLinkLabel}
      </a>
      {header && <div className="ori-app-shell__header">{header}</div>}
      <div className="ori-app-shell__body">
        {sidebar && (
          <>
            <aside className="ori-app-shell__sidebar" aria-label="Navigation latérale">
              {sidebar}
            </aside>
            {onSidebarOpenChange && (
              <button
                type="button"
                className="ori-app-shell__sidebar-toggle"
                aria-label={sidebarOpen ? collapseSidebarLabel : expandSidebarLabel}
                aria-expanded={sidebarOpen}
                aria-controls={MAIN_ID}
                onClick={() => onSidebarOpenChange(!sidebarOpen)}
              >
                {sidebarOpen ? (
                  <ChevronLeft size={16} aria-hidden="true" />
                ) : (
                  <ChevronRight size={16} aria-hidden="true" />
                )}
              </button>
            )}
            <div
              className="ori-app-shell__scrim"
              role="button"
              tabIndex={-1}
              aria-label={closeSidebarLabel}
              onClick={closeSidebar}
            />
          </>
        )}
        <main id={MAIN_ID} tabIndex={-1} className="ori-app-shell__main">
          {children}
        </main>
      </div>
      {footer && <div className="ori-app-shell__footer">{footer}</div>}
    </div>
  );
});
