// packages/react/src/components/Spinner/Spinner.tsx
import { forwardRef } from 'react';
import { clsx } from 'clsx';

/**
 * Spinner inline accessible.
 *
 * Indicateur de chargement compact, destiné à se glisser dans un bouton, un
 * champ ou un texte sans imposer de taille fixe au parent. Pour les
 * chargements pleine page, utiliser le Skeleton ou un overlay applicatif
 * dédié plutôt qu'un Spinner.
 *
 * a11y :
 * - `role="status"` (annonce polite par défaut)
 * - `aria-label` requis (ex : "Chargement…", "Vérification…", "Envoi…")
 * - `aria-hidden="true"` sur le SVG pour ne pas dupliquer le label
 *
 * Couleur : héritée du contexte via `currentColor` ; pour forcer une teinte,
 * appliquer une classe Tailwind ou une CSS variable au parent.
 */

export type SpinnerSize = 'sm' | 'md' | 'lg';

export interface SpinnerProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'aria-label'> {
  /** Taille : sm = 12px, md = 16px (défaut), lg = 20px. */
  size?: SpinnerSize;
  /** Label accessible annoncé par les lecteurs d'écran. */
  label?: string;
}

const sizeMap: Record<SpinnerSize, number> = { sm: 12, md: 16, lg: 20 };

export const Spinner = forwardRef<HTMLSpanElement, SpinnerProps>(function Spinner(
  { size = 'md', label = 'Chargement…', className, ...rest },
  ref,
) {
  const px = sizeMap[size];
  return (
    <span
      ref={ref}
      role="status"
      aria-label={label}
      className={clsx('ori-spinner', `ori-spinner--${size}`, className)}
      {...rest}
    >
      <svg
        className="ori-spinner__svg"
        viewBox="0 0 16 16"
        width={px}
        height={px}
        aria-hidden="true"
        focusable="false"
      >
        <circle
          cx="8"
          cy="8"
          r="6"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeDasharray="28 12"
        />
      </svg>
    </span>
  );
});

// packages/angular/src/components/spinner/spinner.component.ts
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from '@angular/core';

export type OriSpinnerSize = 'sm' | 'md' | 'lg';

/**
 * Spinner inline accessible.
 *
 * Indicateur de chargement compact pour bouton, champ ou texte. Pour les
 * chargements pleine page, utiliser un overlay applicatif dédié.
 *
 * a11y :
 * - role="status" (annonce polite par défaut)
 * - aria-label requis (par défaut "Chargement…")
 * - SVG en aria-hidden pour ne pas dupliquer le label
 *
 * Couleur : héritée du parent via currentColor.
 */
@Component({
  selector: 'ori-spinner',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <span role="status" [attr.aria-label]="label" [class]="'ori-spinner ori-spinner--' + size">
      <svg
        class="ori-spinner__svg"
        viewBox="0 0 16 16"
        [attr.width]="px"
        [attr.height]="px"
        aria-hidden="true"
        focusable="false"
      >
        <circle
          cx="8"
          cy="8"
          r="6"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-dasharray="28 12"
        />
      </svg>
    </span>
  `,
})
export class OriSpinnerComponent {
  /** Taille : sm = 12px, md = 16px (défaut), lg = 20px. */
  @Input() size: OriSpinnerSize = 'md';
  /** Label accessible annoncé par les lecteurs d'écran. */
  @Input() label: string = 'Chargement…';

  protected get px(): number {
    return this.size === 'sm' ? 12 : this.size === 'lg' ? 20 : 16;
  }
}
